import type { IconName } from "@realm/ui";
import type { TeamActivity, VaultAllow, VaultGrant, VaultSecretKind, VaultSecrets, VaultUse } from "@realm/contracts";

/** One secret as the Vault page draws its row and its sheet. */
export type VaultEntry = {
  id: string;
  kind: VaultSecretKind;
  /** "tiktok.com · nathan", "REVENUECAT_SECRET_KEY". */
  name: string;
  glyph: IconName;
  /** The quieter line: what it is, where it may go, who may use it. */
  detail: string;
  /** The hosts it is pinned to: a sign-in's one, a key's own. */
  pinned: string[];
  grants: VaultGrant[];
  allows: VaultAllow[];
  lastUsed: number | null;
  /** The team's own — saved in this Vault, removable here. A profile's sign-in granted to a role is
   *  listed but stays the profile's, removed from Settings ▸ Sign-ins. */
  teamOwned: boolean;
};

const hostOf = (origin: string): string => {
  try { return new URL(origin).host; } catch { return origin; }
};
/** A sign-in by its site and account: the host without `www.`, as realm-server names it. */
export const signinTitle = (origin: string, username: string): string => {
  const host = hostOf(origin).replace(/^www\./, "");
  return username ? `${host} · ${username}` : host;
};

const SITE_GLYPH: [RegExp, IconName][] = [[/tiktok/, "tiktok"], [/instagram/, "instagram"], [/youtube/, "youtube"], [/mail|gmail|outlook/, "mail"]];
const siteGlyph = (origin: string): IconName => SITE_GLYPH.find(([re]) => re.test(origin))?.[1] ?? "padlock";

const names = (grants: VaultGrant[], roleName: (id: string) => string | null): string =>
  grants.map((g) => roleName(g.roleId)).filter(Boolean).join(", ");

/**
 * The team's secrets as rows: its own sign-ins and keys, and any of the profile's sign-ins it has
 * granted to a role. A profile sign-in nobody here was granted is not the team's business and is not
 * listed (Add ▸ "From your sign-ins" is where it is picked).
 */
export function vaultEntries(
  secrets: VaultSecrets, allows: VaultAllow[], grants: VaultGrant[], uses: VaultUse[], spaceId: string, roleName: (id: string) => string | null,
): { signins: VaultEntry[]; keys: VaultEntry[] } {
  const last = new Map<string, number>();
  for (const u of uses) if (u.secretId && u.outcome !== "refused" && !last.has(u.secretId)) last.set(u.secretId, u.ts);
  const of = (id: string) => grants.filter((g) => g.secretId === id);
  const signins = secrets.signins
    .filter((s) => s.spaceId === spaceId || of(s.id).length > 0)
    .map((s): VaultEntry => {
      const who = names(of(s.id), roleName);
      const what = s.label ? `Sign-in for ${s.label}` : s.generated ? "Sign-in · generated by Realm" : s.spaceId === spaceId ? "Sign-in" : "Your sign-in, from Settings";
      return {
        id: s.id, kind: "signin", name: signinTitle(s.origin, s.username), glyph: siteGlyph(s.origin),
        detail: [what, who || "No role may use it"].join(" · "), pinned: [hostOf(s.origin)],
        grants: of(s.id), allows: allows.filter((a) => a.secretId === s.id), lastUsed: last.get(s.id) ?? null, teamOwned: s.spaceId === spaceId,
      };
    });
  const keys = secrets.keys.map((k): VaultEntry => {
    const who = names(of(k.id), roleName);
    return {
      id: k.id, kind: "key", name: k.name, glyph: "key",
      detail: [`API key · only to ${k.allowedHosts.join(", ")}`, who || "No role may use it"].join(" · "), pinned: k.allowedHosts,
      grants: of(k.id), allows: allows.filter((a) => a.secretId === k.id), lastUsed: last.get(k.id) ?? null, teamOwned: true,
    };
  });
  return { signins, keys };
}

/** One row of Recent use, in the mock's columns: what happened, and where — or, refused, why. */
export function useLine(u: VaultUse): { what: string; where: string; chip: { word: string; tone: "ok" | "warn" } } {
  if (u.outcome === "refused") return { what: `Asked for ${u.secretName}`, where: u.where, chip: { word: "Refused", tone: "warn" } };
  if (u.kind === "signin") return { what: `Filled ${u.secretName}`, where: u.where, chip: { word: "Filled", tone: "ok" } };
  return { what: `${u.secretName} into one request`, where: u.where, chip: { word: "Used", tone: "ok" } };
}

/** The vault's lines in the team's Activity, or null for a verb that is not the vault's. */
export function vaultSentence(a: TeamActivity, actorName: string): { text: string; detail: string | null } | null {
  const d = a.detail;
  const role = typeof d.role === "string" ? d.role : "a role";
  const where = typeof d.where === "string" ? d.where : null;
  const hosts = Array.isArray(d.hosts) ? (d.hosts as string[]).join(", ") : null;
  switch (a.verb) {
    case "used_secret":
      return { text: d.kind === "signin" ? `${actorName} filled ${a.object}` : `${actorName} used ${a.object}`,
        detail: [where, d.how === "unattended" ? "without asking" : "on its card"].filter(Boolean).join(" · ") };
    case "refused_secret": return { text: `${actorName} was refused ${a.object}`, detail: typeof d.reason === "string" ? d.reason : null };
    case "granted_secret": return { text: `You let ${role} use ${a.object}`, detail: hosts };
    case "regranted_secret": return { text: `You changed where ${role} may use ${a.object}`, detail: hosts };
    case "revoked_secret": return { text: `You took ${a.object} away from ${role}`, detail: null };
    case "allowed_unattended": return { text: `You let ${role} use ${a.object} without asking`, detail: hosts ? `on this Mac · ${hosts}` : "on this Mac" };
    case "asked_again": return { text: `You set ${role} to ask again before it uses ${a.object}`, detail: null };
    default: return null;
  }
}
