/**
 * `target` cases: on this screen, the words an agent might use for what it wants, and the element
 * that does it. Screen id → element → phrasings.
 *
 * An element is named by its label exactly, `~` + the start of its label, or `label#2` for the second
 * element with that label. `a | b` accepts either element (the same thing drawn twice, say a widget and
 * an icon for one app); the first is the one recorded.
 *
 * The rule for every phrasing: a careful person looking at this screen would tap this element and no
 * other. Most do not repeat the element's words — "pair my AirPods" rather than "Bluetooth" — because
 * those are the only ones Laya is ever asked about: a walk finds a label it was given by matching it.
 */
export const TARGET: Record<string, Record<string, string[]>> = {
  home: {
    Safari: ["browse the web", "open a website", "the web browser"],
    Messages: ["text my mom", "send an SMS", "read my texts"],
    Photos: ["look at my pictures", "my camera roll"],
    Health: ["check my heart rate history", "see how I slept last night"],
    Wallet: ["show my boarding pass", "use Apple Pay at the register"],
    News: ["read today's headlines"],
    Settings: ["change my wallpaper", "adjust screen brightness", "turn on airplane mode"],
    "Maps#1 | Maps#2": ["directions to the airport", "how long is the drive to work"],
    "Calendar#2 | Calendar#1": ["what's on my schedule today", "when is my next meeting"],
    Siri: ["ask the voice assistant a question"],
  },

  "settings-root-top": {
    General: ["check for a software update", "change the phone's language", "set up a VPN", "find my phone's model number", "add a keyboard in another language"],
    Accessibility: ["vision settings", "turn on VoiceOver", "features for people who are hard of hearing", "enable closed captions", "make the phone easier to use with low vision"],
    "Action Button": ["remap the silent switch", "choose what the side shortcut key does"],
    Appearance: ["turn on dark mode", "switch the phone to light mode", "make the text bold", "night theme with black backgrounds"],
    Camera: ["record video in 4K", "turn on the grid lines for photos", "shoot photos in HEIC or JPEG"],
    "Home Screen & App Library": ["keep new downloads off my first page"],
    Search: ["Spotlight suggestions"],
    Siri: ["change the voice assistant's voice", "turn on Hey Siri"],
    StandBy: ["nightstand clock mode while charging", "the landscape bedside display"],
    "Screen Time": ["parental controls", "set limits on my kid's apps", "see how long I spend on my phone"],
    Passcode: ["change my unlock code", "Face ID settings", "turn off the lock code"],
    "Privacy & Security": ["see which apps can use my location", "stop apps from tracking me", "camera and microphone permissions"],
    "~Apple Account": ["sign in with my Apple ID"],
  },
  "settings-root-3": {
    "Game Center": ["gaming profile and achievements", "friends I play games with"],
    iCloud: ["back up my phone to the cloud", "turn on cloud photo sync"],
    Apps: ["change Safari's settings", "per-app settings like Messages and Mail", "turn off read receipts in Messages"],
    Developer: ["debugging and testing options"],
    Passcode: ["require a PIN to unlock"],
    "Privacy & Security": ["location services", "which apps can see my contacts"],
  },
  "settings-accessibility-2": {
    "VoiceOver, Off": ["screen reader for blind users", "have the phone describe what's on the screen"],
    "Display & Text Size": ["invert colors", "color filters for color blindness", "increase contrast"],
    Motion: ["stop the parallax and animations", "less movement on screen"],
    "Spoken Content": ["have the phone read selected text aloud", "speak the screen"],
    "Face ID & Attention": ["require looking at the phone to unlock"],
    "Control Nearby Devices": ["operate my iPad from this phone"],
    "Subtitles & Captioning": ["closed captions on videos", "SDH subtitles"],
    "Live Speech, Off": ["type words and have them said out loud in a call"],
    "Keyboards & Typing": ["sticky keys", "slow keys for a physical keyboard"],
    "Hover Text, Off": ["show a big version of whatever my pointer is over"],
  },
  "settings-appearance": {
    "9:41, Dark": ["night theme with a black background", "the dark look"],
    "9:41, Light": ["white background theme", "the bright look"],
    Automatic: ["switch themes at sunset by itself"],
    "Text Size": ["make words bigger", "larger font everywhere"],
    "Bold Text": ["heavier font weight", "thicker letters"],
    "Display Zoom, Default": ["make icons and controls bigger"],
    "Reduce Motion": ["fewer animations", "stop things sliding around"],
    "Liquid Glass, Default": ["make menus less see-through"],
  },
  "settings-camera": {
    "Record Video, 1080p at 30 fps": ["shoot in 4K at 60", "change the video resolution"],
    "Record Slo-mo, 1080p at 120 fps": ["slow motion frame rate", "240 fps capture"],
    Formats: ["save photos as HEIC or JPEG", "ProRAW settings"],
    Grid: ["rule of thirds lines", "guides over the viewfinder"],
    Level: ["keep the horizon straight when I shoot"],
    "Mirror Front Camera": ["stop flipping my selfies"],
    "Preserve Settings": ["remember the last camera mode I used"],
    "View Outside the Frame": ["show what's beyond the crop while framing"],
  },
  "settings-general": {
    About: ["find my serial number", "what iOS version am I on", "how much storage does this phone have"],
    "AutoFill & Passwords": ["stop suggesting saved logins", "which app fills in my passwords"],
    Dictionary: ["add a Spanish word lookup"],
    Fonts: ["installed typefaces", "add a custom typeface"],
    Keyboard: ["turn off autocorrect", "add the emoji keyboard", "text replacement shortcuts"],
    "Language & Region": ["switch the phone to French", "use Celsius", "change my country"],
    "VPN & Device Management": ["remove my work profile", "MDM profiles"],
    "Screen Capture": ["what happens after I take a screenshot"],
  },
  "settings-about": {
    "~Serial Number": ["the device's serial"],
    "~iOS Version": ["which software release is installed"],
    "~Available": ["how much free space is left"],
    "~Model Number": ["the part number of this phone"],
    "Certificate Trust Settings": ["trust a root certificate I installed"],
    "~Name, iPhone": ["rename this phone"],
  },
  "settings-keyboard": {
    "Text Replacement": ["make omw expand to on my way", "typing shortcuts"],
    "Keyboards, 2": ["add a Japanese keyboard", "remove the emoji keyboard"],
    "One-Handed Keyboard, Off": ["shift the keys to one side for typing with a thumb"],
    "Haptic Feedback": ["make the keys vibrate"],
    Sound: ["keyboard click noise"],
    "Auto-Correction": ["stop fixing my spelling as I type", "turn off autocorrect"],
    "Auto-Capitalization": ["stop capitalizing the first word of a sentence"],
    "Predictive Text": ["hide the word suggestions above the keys"],
    "Enable Caps Lock": ["double-tap shift for all caps"],
    "Smart Punctuation": ["use straight quotes instead of curly ones"],
    "Check Spelling and Grammar": ["underline typos in red"],
  },
  "settings-fonts": {
    "System Fonts": ["the typefaces that ship with iOS"],
    "My Fonts": ["typefaces I installed myself"],
  },
  "settings-language": {
    "Temperature, °F": ["show degrees in Celsius"],
    "Measurement System, US": ["use kilometers instead of miles", "metric units"],
    "Region, United States": ["set my country to Canada"],
    "Add Language…": ["add Japanese as a preferred language"],
    "Number Format, 1, 234, 567.89": ["use commas as decimal separators"],
    "First Day of Week, Sunday": ["start weeks on Monday"],
    "Date Format, 8/19/26": ["show dates as day then month"],
    "Calendar, Gregorian": ["use the Hebrew calendar"],
    "Live Text": ["recognize words in pictures"],
  },
  "settings-privacy-1": {
    "Location Services, 1 while using": ["GPS permissions", "which apps know where I am"],
    "Calendars, None": ["apps that can see my events"],
    "Contacts, None": ["which apps can read my address book"],
    "Health, None": ["apps reading my step counts"],
    "Media & Apple Music, None": ["apps accessing my song library"],
    "Focus, None": ["apps that can see my Do Not Disturb status"],
    "Home, None": ["apps controlling my smart lights and thermostat"],
    "Files & Folders, None": ["apps that can open my documents"],
  },
  "settings-privacy-2": {
    "Photos, None": ["which apps can see my pictures"],
    "Bluetooth, 0": ["apps allowed to find AirPods and speakers"],
    "Camera, 1": ["apps that can take pictures"],
    "Microphone, 0": ["apps that can listen through the mic"],
    "Motion & Fitness, 0": ["apps that read my accelerometer"],
    "Local Network, 0": ["apps finding devices on my home Wi-Fi"],
    "Reminders, None": ["apps that can read my to-dos"],
    "Wallet, None": ["apps that can see my passes and cards"],
  },
  "settings-privacy-3": {
    "Speech Recognition, 0": ["apps that transcribe what I say"],
    "Blocked Contacts": ["numbers I've stopped from calling me"],
    "Safety Check": ["cut off access for an abusive partner", "stop sharing my location with everyone at once"],
    "Analytics & Improvements": ["stop sending diagnostic data to Apple"],
    "Apple Advertising": ["turn off targeted ads in the App Store"],
    "Sensitive Content Warning, On": ["blur nude images people send me"],
    "Research Sensor & Usage Data, 0": ["studies collecting my sensor data"],
  },
  "settings-screentime": {
    "Apps & Websites, Limit Adult Websites": ["keep porn off the browser", "restrict mature sites"],
    "Screen Time Schedule, Available device hours": ["bedtime downtime hours", "hours when the phone is locked down"],
    "Allowed Contacts, Everyone": ["who my kid can call and text"],
    "Always Allowed, Not Set Up": ["apps usable even during limits"],
    "Time Allowances, Allowed time for content categories": ["an hour a day for games"],
    "Content & Privacy Restrictions, Explicit": ["stop in-app purchases", "block explicit music"],
    "Communication Safety, On": ["warn my child before they view nudity"],
  },
  "settings-safari-1": {
    "Search Engine, Google": ["switch to DuckDuckGo", "use Bing for searches"],
    "Default Browser App, Safari": ["make Chrome open my links"],
    "Start Page Favorites, Favorites": ["which bookmarks show on a new tab"],
    AutoFill: ["fill in my address on web forms"],
    "Preload Top Hit": ["start loading the best result before I tap it"],
  },
  "settings-safari-2": {
    "Block Pop-ups": ["stop windows opening by themselves"],
    Extensions: ["install an ad blocker", "content blockers"],
    "Downloads, On My iPhone": ["where saved files go"],
    "Close Tabs, Manually": ["auto-close old tabs after a week"],
    "Open Links, In New Tab": ["open links in the background"],
    Bottom: ["put the address bar at the bottom"],
  },
  "settings-safari-3": {
    "Prevent Cross-Site Tracking": ["stop sites following me around the web"],
    "Fraudulent Website Warning": ["warn me about phishing pages", "alert me about scam sites"],
    "New Profile": ["separate browsing for work and personal"],
    "Require Passcode to Unlock Private Browsing": ["lock my incognito tabs with Face ID"],
    "Hide IP Address, Off": ["mask my IP from trackers"],
  },
  "settings-safari-4": {
    "Clear History and Website Data": ["delete cookies and cache", "wipe my browsing history"],
    Import: ["bring in bookmarks from Chrome"],
    Export: ["back up my bookmarks to a file"],
    Microphone: ["let websites use my mic"],
    Location: ["websites asking where I am"],
    Advanced: ["JavaScript and web inspector settings"],
    Reader: ["always open articles in the clean reading view"],
    "Automatically Save Offline": ["keep saved articles available without internet"],
  },
  "settings-clear-history": {
    "Last hour": ["just the past 60 minutes"],
    "All history": ["everything since I started using Safari"],
    "Today and yesterday": ["the past two days"],
  },
  "settings-siri": {
    "Voice, American (Voice 4)": ["make Siri sound British", "a different voice for the assistant"],
    ChatGPT: ["OpenAI integration"],
    Responses: ["have Siri answer silently with text"],
    "Your Information, None": ["tell Siri which contact card is me"],
    "Language, English (United States)": ["talk to Siri in Spanish"],
    "App Access": ["which apps work with the assistant"],
  },
  "settings-standby": {
    Display: ["keep the bedside screen always on at night"],
    "Show Notifications": ["hide alerts while docked on the charger"],
  },
  "settings-homescreen": {
    "App Library Only": ["keep new downloads off my home pages"],
    "Add to Home Screen": ["put every new app on my home pages"],
  },
  "settings-search": {
    "Show Recent Searches": ["stop Spotlight showing my old queries"],
    "Help Apple Improve Search": ["share my queries to make results better"],
    "Suggest Apps": ["recommend apps before I type"],
  },
  "settings-autofill": {
    "Delete After Use": ["remove two-factor codes from Messages once used"],
    "Suggest Strong Passwords": ["generate secure random passwords"],
  },
  "settings-location": {
    "Share My Location": ["let family see where I am"],
    "~System Services": ["location use by iOS itself"],
    "Location Alerts": ["reminders that fire when I arrive somewhere"],
  },
  "settings-apps": {
    "Default Apps, Manage default apps on iPhone": ["set Chrome as my browser", "choose which mail app opens links"],
    Messages: ["iMessage settings", "turn off read receipts"],
    Fitness: ["activity rings settings"],
    Files: ["document browser settings"],
  },
  "settings-apps-2": {
    Preview: ["PDF viewer settings"],
    Shortcuts: ["automation app settings"],
    Safari: ["web browser settings"],
    Remote: ["settings for controlling my Apple TV"],
    Passwords: ["password manager settings"],
  },
  "settings-signin-sheet": {
    "~Use Another Apple Device": ["sign in using my iPad nearby"],
    "~Don’t have an Apple Account?": ["create a new account"],
  },
  "settings-signin-email": {
    "Sign in a Child in My Family": ["set up an account for my son"],
  },
  "settings-displayzoom": {
    "Larger Text": ["bigger controls and text"],
  },
  "settings-liquidglass": {
    "Tint Amount": ["make the glass more opaque"],
  },
  "settings-textsize": {
    "More in Accessibility Settings…": ["even larger sizes than the slider allows"],
  },

  "safari-start": {
    "Page Menu": ["page options like find and zoom"],
    Tabs: ["see all open pages"],
    refresh: ["reload the page"],
  },
  "safari-pagemenu": {
    "Find on Page": ["search for a word in this article", "ctrl-F"],
    "Page Zoom": ["make the text on this site bigger"],
    "Request Desktop Website": ["see the full computer version of this site"],
    "Hide Distracting Items": ["remove clutter from the page"],
    "Hide Toolbar": ["full-screen reading without the address bar"],
    "Website Settings…": ["let this site use my camera"],
    "Report Website Issue": ["tell Apple this page is broken"],
    "Notify Me": ["get alerts when this site updates"],
    Share: ["send this link to a friend"],
    "Customize Menu": ["rearrange this menu"],
    "Tab Actions": ["pin or move this tab"],
  },
  "safari-share": {
    Copy: ["put the link on the clipboard"],
    "Add to Reading List": ["save it to read offline later"],
    "Options": ["share as a PDF instead of a link"],
    Reminders: ["remind me to read this tomorrow"],
  },
  "safari-tabs": {
    add: ["open a new tab", "a blank page"],
    "Private, Tab Group": ["incognito mode", "browse without saving history"],
    Done: ["go back to the page I was reading"],
    Search: ["find a tab by name"],
    Close: ["dismiss the tip about swiping"],
  },
  "safari-newtab": {
    Bing: ["Microsoft's search engine"],
    Google: ["the search engine owned by Alphabet"],
    Yahoo: ["the old purple web portal"],
    History: ["pages I visited yesterday"],
    "Reading List": ["articles saved for offline"],
    Bookmarks: ["my saved sites"],
    Edit: ["customize the start page sections"],
    Tabs: ["switch between open pages"],
  },
  "safari-address": {
    Close: ["hide the keyboard and stop typing a URL"],
    Emoji: ["insert a smiley"],
    go: ["load the page I typed"],
    shift: ["type a capital letter"],
    delete: ["backspace"],
  },
  "safari-bookmarks-more": {
    "Sort By, None": ["alphabetize my bookmarks"],
    Compact: ["a denser list"],
    Large: ["bigger thumbnails"],
    "Show Folders on Top": ["list the folders first"],
  },
  "safari-private": {
    "Not Now": ["skip this"],
  },
  "safari-typed": {
    "Clear text": ["erase what I typed"],
  },

  "maps-root": {
    "clear, 67 degrees, Air Quality, 51, Moderate": ["how hot is it outside", "today's forecast"],
    "Map Modes": ["switch to satellite view", "show public transit lines"],
    "Look Around": ["street-level imagery"],
    profile: ["my Maps account and preferences"],
    "Home, Add": ["save my house address"],
    "Work, Add": ["save my office location"],
    "Favorites, 0 places": ["my saved spots"],
    "San Francisco Museum of Modern Art": ["SFMOMA"],
    "Dragon Gate": ["the entrance to Chinatown"],
    "Jollibee, Restaurant": ["the Filipino fried chicken place"],
    "Grace Cathedral": ["the big church on Nob Hill"],
    Arsicault: ["that famous croissant bakery"],
    Embarcadero: ["the waterfront by the Ferry Building"],
    "Union Square": ["the shopping plaza with Macy's"],
    "Powell St": ["the BART station at the cable car turnaround"],
  },
  "maps-search": {
    "Gas Stations": ["fill up the car"],
    Hikes: ["trails to walk"],
    Lunch: ["somewhere for a midday meal"],
    "~Ippudo": ["tonkotsu noodle soup"],
    "~Advertisement, Corzetti": ["handmade pasta"],
    "~Morella": ["empanadas and chimichurri"],
    "The most romantic restaurants in SF": ["date night ideas"],
  },
  "maps-coffee": {
    "~Breakfast Spots": ["where to get brunch"],
    "Clear text": ["erase what I typed in search"],
    "Close": ["stop searching"],
  },
  "maps-place": {
    "Call | ~Phone, +1": ["ring them up"],
    Menu: ["see what drinks they serve"],
    "2 min, walking": ["how do I get there on foot"],
    "Report an Issue": ["tell Apple the hours are wrong"],
    Pin: ["drop a marker for this place"],
    Favorite: ["star this place so I can find it again"],
    "Ratings & Reviews": ["what do people say about it"],
    "Website | ~Website, peets.com": ["their homepage"],
    Share: ["send this place to a friend"],
    Close: ["dismiss this place card"],
  },
  "maps-directions": {
    Ride: ["get an Uber"],
    Cycle: ["bike there"],
    Transit: ["take the bus"],
    Drive: ["go by car"],
    Steps: ["turn-by-turn list of the route"],
    Options: ["avoid hills and busy roads"],
    "3D mode": ["tilt the map to see buildings"],
  },
  "maps-modes": {
    Satellite: ["aerial photo view"],
    Driving: ["show traffic and road conditions"],
    Transit: ["show subway and bus lines"],
    Explore: ["the standard default map"],
  },
  "maps-satellite": {
    Traffic: ["show congestion on roads"],
    Labels: ["hide street names on the aerial image"],
  },
  "maps-permission": {
    "Allow Once": ["just this one time"],
    "Don’t Allow": ["keep my location private from Maps"],
  },
  "maps-ads-notice": {
    "About Apple Advertising & Privacy…": ["read how the ads use my data"],
  },

  "calendar-root": {
    "Wednesday, September 30": ["tomorrow"],
    "Monday, September 28": ["yesterday"],
    Inbox: ["event invitations"],
    September: ["see the whole month"],
    Add: ["schedule a new meeting"],
    Search: ["find the dentist appointment"],
    "Friday, October 2": ["the end of this work week"],
    "Today | Today, Tuesday, September 29": ["jump back to the current date"],
  },
  "calendar-month": {
    "Monday, September 7": ["Labor Day"],
    "Tuesday, September 22": ["a week ago today"],
    "Wednesday, September 30": ["the last day of this month"],
    "Thursday, October 1": ["the first day of next month"],
    "2026": ["the whole year view"],
  },
  "calendar-new-event": {
    "Location or Video Call": ["add a Zoom link", "where the meeting is"],
    "Alert, None": ["remind me 10 minutes before"],
    "Travel Time, None, None": ["account for the drive there"],
    "Add attachment…": ["attach the agenda PDF"],
    Cancel: ["discard this event"],
    Reminder: ["make it a to-do instead"],
    "12 PM – 1 PM": ["change when it starts and ends"],
  },
  "calendar-calendars": {
    "US Holidays, Subscribed": ["federal days off"],
    "Show Completed Reminders": ["show finished tasks"],
    "Add Calendar": ["subscribe to a sports schedule"],
    close: ["done with this list"],
  },
  "calendar-discard": {
    "Discard Changes": ["throw away the draft"],
  },

  "contacts-card": {
    Message: ["text John", "send him an iMessage"],
    Call: ["ring him"],
    Video: ["FaceTime him"],
    Mail: ["email him"],
    "mobile, (888) 555-5512": ["his cell number"],
    "~work, 3494 Kuhl Avenue": ["directions to his office"],
    "~home, 1234 Laurel Street": ["drive to his house"],
    Edit: ["change his details"],
  },
  "contacts-anna": {
    "birthday, August 29, 1985": ["when she was born"],
    "anniversary, February 15, 2002": ["her wedding date"],
    "~home, 1001": ["navigate to Anna's place"],
    Video: ["FaceTime Anna"],
  },
  "contacts-list": {
    "~Hank M. Zakroff": ["my banker"],
    "Daniel Higgins Jr.": ["the one who's a junior"],
    Add: ["new contact"],
  },
  "contacts-edit": {
    "Add photo": ["give her a profile picture"],
    "add phone": ["a second number for her"],
    "add pronouns": ["she/her"],
    close: ["stop editing without saving"],
  },
  "contacts-edit-2": {
    "add related name": ["note that she's my sister"],
    "add social profile": ["her Instagram handle"],
    "add instant message": ["her WhatsApp username"],
    "add field": ["add a middle name"],
    "Add to Emergency Contacts": ["make her my ICE contact"],
    "link contacts…": ["merge with her duplicate card"],
    "add to list": ["put her in my family group"],
    "Delete Contact": ["remove her from my phone"],
    "add date": ["remember her graduation day"],
  },

  "messages-thread": {
    add: ["attach a photo"],
    "+1 (888) 555-1212": ["see contact details for this chat"],
    Back: ["all conversations"],
  },
  "messages-compose": {
    Send: ["deliver this text"],
  },
  "messages-add": {
    "Apple Cash": ["send money"],
    Audio: ["record a voice memo"],
    "#images": ["find a GIF"],
    "Check In": ["let them know I got home safely"],
    Camera: ["take a picture now"],
    Photos: ["choose a picture from my library"],
    "Digital Touch": ["send a sketch or my heartbeat"],
  },

  "photos-root": {
    "Sort and Filter": ["show only favorites"],
    Select: ["choose several pictures"],
    Collections: ["browse my albums"],
    Search: ["find pictures of dogs"],
  },
  "photos-photo": {
    Share: ["send this picture to someone"],
    Favorite: ["heart this picture"],
    Info: ["when was this taken"],
    Edit: ["crop this picture"],
    Delete: ["trash this picture"],
    Back: ["return to the grid"],
  },
  "photos-info": {
    Adjust: ["fix the date it was taken"],
    Location: ["where it was shot"],
    "Add Keywords": ["tag it"],
  },
  "photos-edit": {
    Filters: ["make it black and white", "a vintage look"],
    Adjust: ["brighten the exposure"],
    "Crop and Rotate": ["trim the edges"],
    Flip: ["mirror the image"],
    Rotate: ["turn it sideways"],
    "Aspect Ratio": ["make it square"],
    Cancel: ["leave without saving edits"],
  },
  "photos-collections": {
    "Recently Deleted": ["recover a picture I trashed"],
    Map: ["photos by where they were taken"],
    Videos: ["clips I recorded"],
    Screenshots: ["captures of my display"],
    Create: ["start a new album"],
    Favorites: ["my starred pictures"],
  },

  "files-root": {
    Browse: ["see all my folders and drives"],
  },
  "files-browse": {
    Recents: ["documents I opened lately"],
    More: ["options for this folder"],
  },
  "files-more": {
    "New Folder": ["create a directory"],
    "Scan Documents": ["digitize a paper receipt with the camera"],
    "Connect to Server": ["open an SMB network share"],
    Icons: ["show files as thumbnails"],
    List: ["show files as rows"],
    "Name, Ascending": ["sort alphabetically"],
    Kind: ["group by file type"],
    Date: ["newest first"],
    Size: ["biggest files first"],
    Tags: ["sort by color labels"],
    Select: ["pick several files at once"],
  },

  "reminders-lists": {
    "All, 0 reminders": ["everything on my to-do list"],
    Completed: ["tasks I've finished"],
    "Go to Settings": ["turn on iCloud sync"],
    Close: ["dismiss the sync banner"],
    "New Reminder": ["new to-do"],
    "Today, 0 reminders, September 29": ["what's due now"],
  },
  "reminders-new": {
    Location: ["remind me when I get home"],
    Flag: ["mark it as important"],
    Photos: ["attach a picture"],
    Details: ["set priority and tags"],
    Done: ["save the reminder"],
    Cancel: ["never mind"],
  },
  "reminders-more": {
    "Show List Info": ["rename the list and change its color"],
    "Select Reminders": ["tick off several at once"],
    "Sort By, Manual": ["order by due date"],
    "Show Completed": ["see tasks I've finished"],
    Print: ["a paper copy"],
  },
  "reminders-delete-alert": {
    Delete: ["yes, remove it"],
    Cancel: ["keep the list"],
  },
  "reminders-icloud-alert": {
    "Not Now": ["skip syncing"],
    "Go to Settings": ["enable iCloud sync"],
  },

  "shortcuts-library": {
    "Apple Watch": ["shortcuts on my wrist"],
    Gallery: ["ready-made shortcuts"],
    Automation: ["run something at sunrise"],
    "Share Sheet": ["shortcuts that appear when I tap the export button"],
  },
  "shortcuts-root": {
    "New Shortcut": ["build a custom automation"],
    Library: ["see my shortcut folders"],
  },
  "shortcuts-gallery": {
    "Add, Start Pomodoro": ["a focus timer"],
    "Add, Haiku": ["write a short Japanese poem"],
    "Add, Morning Summary": ["a daily briefing when I wake up"],
    "Add, Batch Add Reminders": ["create many to-dos at once"],
    "Shortcuts for Accessibility": ["shortcuts for people with disabilities"],
  },

  "health-browse": {
    Activity: ["exercise minutes"],
    "Body Measurements": ["my BMI"],
    "Cycle Tracking": ["log my period"],
    Hearing: ["headphone volume levels"],
    Heart: ["blood pressure"],
    Medications: ["pills I take"],
    "Mental Wellbeing": ["log my mood"],
    Mobility: ["walking steadiness"],
    Nutrition: ["calories I ate"],
    Respiratory: ["breathing rate"],
    Sleep: ["how long I slept"],
    Symptoms: ["log a headache"],
  },
  "health-heart": {
    "AFib History": ["atrial fibrillation burden"],
    "Blood Pressure": ["BP readings"],
    "Cardio Fitness": ["VO2 max"],
    "Electrocardiograms (ECG)": ["my EKG"],
    "Heart Rate Variability": ["HRV"],
    "Browse#1 | Browse#2": ["back to the categories"],
  },
  "health-summary": {
    Profile: ["my medical details"],
    "Steps, No Data": ["how far I walked today"],
    Edit: ["choose what's pinned"],
  },
  "health-sharing": {
    "Share with your doctor": ["send my records to my physician"],
    "Research Studies": ["join a clinical trial"],
    "Ask Someone to Share": ["see my mom's health data"],
    "Share with Someone": ["let my partner see my data"],
  },
  "health-setup-2": {
    Next: ["skip this step"],
    Height: ["how tall I am"],
    Sex: ["my gender"],
    "Last Name": ["my surname"],
  },
  "health-setup-1": {
    "Learn more…": ["read about data protection"],
  },

  "wallet-root": {
    "Add Card": ["add my Visa"],
    Orders: ["track my packages"],
    More: ["Wallet preferences"],
    Search: ["find a pass"],
  },
  "wallet-more": {
    AutoFill: ["fill my card in automatically when shopping online"],
    Notifications: ["alerts about transactions"],
  },
  "wallet-orders": {
    Done: ["close this list"],
    "Learn More": ["which stores support order tracking"],
  },
  "wallet-error": {
    OK: ["dismiss the error"],
  },

  "passwords-root": {
    "All, 0 Items": ["every saved login"],
    "Codes, 0 Items": ["my two-factor authenticator"],
    "Wi-Fi, 3 Items": ["saved network keys"],
    "Security, 0 Items": ["check for leaked or weak passwords"],
    "Deleted, 0 Items": ["recover a login I removed"],
    "New Password": ["save a new login"],
    "Passkeys, 0 Items": ["FIDO sign-in keys"],
  },
  "passwords-wifi": {
    "Café Wi-Fi, WPA3 Personal": ["the coffee shop network"],
    "Work Wi-Fi, WPA3 Personal": ["the office network"],
    Passwords: ["back to the categories"],
  },
  "passwords-new": {
    Save: ["store this login"],
    Cancel: ["abandon it"],
  },

  "news-root": {
    "Try News+ Free": ["start the premium trial"],
    Sports: ["NBA scores"],
    Puzzles: ["today's crossword"],
    Local: ["news from my city"],
    Entertainment: ["celebrity gossip"],
    Audio: ["listen to stories"],
    Search: ["look up a topic"],
    "News+": ["premium magazines"],
  },
  "news-puzzles": {
    Sudoku: ["the 9x9 number puzzle"],
    Leaderboard: ["how I rank against friends"],
    Quartiles: ["the word tiles game"],
    Back: ["leave the puzzles page"],
  },
  "news-audio": {
    "Play All": ["listen to everything in order"],
    "Try 1 Month Free": ["sign up for the audio subscription trial"],
  },

  "fitness-root": {
    "Account Settings": ["change my move goal and profile"],
    "Edit Your Summary": ["customize this page"],
    Workout: ["go for a run"],
    Sharing: ["compete with friends"],
    "Fitness+": ["guided workout classes"],
    "Step Distance, Today, 0.00MI": ["how far I walked"],
  },
  "fitness-workouts": {
    GymKit: ["connect to a gym treadmill"],
    "Heart Rate Devices": ["pair a chest strap"],
    "Add Workout": ["add yoga to my list"],
    "View Schedule": ["see the training plan calendar"],
  },
  "fitness-buddy": {
    "Use Workout Buddy": ["turn on voice encouragement during exercise"],
  },

  "watch-root": {
    "Start Pairing": ["connect my Apple Watch"],
    Discover: ["shop for watch bands and models"],
  },
  "watch-faces": {
    "Dress Watch, Faces to go with formal attire.": ["something for a black-tie wedding"],
    "Astronomy, Inspired by planetary bodies.": ["stars and space themed"],
    "Nike Collection, Celebrating sport and activity.": ["the swoosh brand designs"],
    "Data Rich, Functional and full of complications.": ["as many widgets as possible"],
    "Clean, Simple and distraction free.": ["minimalist"],
    "Analog Time, Designs with distinct watch hands.": ["an old-fashioned dial"],
    "Digital Time, Clear and glanceable time telling.": ["numbers instead of hands"],
    "Pride Collection, Celebrating the LGBTQ+ community.": ["rainbow designs for June"],
    "Tool Watch, Designed for specific functions.": ["utility faces for divers and pilots"],
    "Playful, All around joy and delight.": ["fun cartoon-like faces"],
    "See All Watch Faces": ["the full catalog"],
  },

  "remote-root": {
    Mute: ["silence the TV"],
    Power: ["turn the TV off"],
    "Play Pause": ["resume the show"],
    Menu: ["go back a screen on the TV"],
  },
  "preview-root": {
    "Scan Documents": ["digitize a paper form"],
    "New Document": ["start a blank page"],
    Browse: ["all my folders"],
    Shared: ["files people sent me"],
  },
};
