/**
 * The real device the stream is laid into, and where it sits in the picture of one.
 *
 * Realm ships three frames — an iPhone, an iPad, a Pixel — and no more, because at the size a pane
 * draws them every modern phone in a family is the same black slab: a table with a row per product
 * is a table that is wrong the September after it is written. The art and the coordinates of each
 * one's screen hole are fetched and generated by `scripts/fetch-device-frames.mjs`; who drew each is
 * in `assets/devices/CREDITS.md`.
 *
 * A device the shipped art is not a picture OF still gets a frame — the one `device-frame.ts` draws
 * out of Realm's own surface. That is the fallback for a watch, an Android tablet, an old 16:9
 * phone, and anything else whose proportions say the art in hand would be a lie about it.
 */

import type { SimulatorPlatform, SimulatorScreen } from "@realm/contracts";
import type { Box } from "../machine/fit";
import { deviceShape, screenRadiusFor } from "./device-frame";
import { DEVICE_ART, type DeviceArt } from "./device-art.generated";

export type DeviceArtFrame = DeviceArt & { src: string };

/**
 * How far a device's proportions may sit from the art's screen before the art is the wrong picture
 * of it, as a fraction.
 *
 * 4% covers the family and excludes the strangers: every iPhone from the 14 through the 17 Pro Max
 * is within 1% of 19.5:9, and the iPhone SE's 16:9 is 18% away — which is the case this exists for.
 * An SE fitted into a Pro's hole is a letterboxed picture inside a Dynamic Island, i.e. a frame that
 * says the device is something it is not.
 */
const ASPECT_TOLERANCE = 0.04;

/** The proportions of a screen, orientation thrown away: a rotated device is the same device. */
const proportions = (width: number, height: number): number =>
  Math.min(width, height) / Math.max(width, height);

/**
 * The frame for this device, or null when Realm has no picture of it and should draw its own.
 *
 * `platform` comes from the row rather than from the shape of a udid — the contract is explicit that
 * it is carried, never inferred — and null means it has not arrived yet, which draws Realm's frame
 * for the moment rather than guessing an iPhone around an emulator.
 */
export function artFor(screen: SimulatorScreen, platform: SimulatorPlatform | null): DeviceArtFrame | null {
  if (!platform) return null;
  const shape = deviceShape(screen);
  const art = platform === "android"
    ? (shape === "phone" ? DEVICE_ART.androidPhone : null)
    : shape === "phone" ? DEVICE_ART.iosPhone : shape === "tablet" ? DEVICE_ART.iosTablet : null;
  if (!art) return null;
  const device = proportions(screen.width, screen.height);
  const hole = proportions(art.screen.width, art.screen.height);
  return Math.abs(device - hole) / hole <= ASPECT_TOLERANCE ? art : null;
}

/**
 * How far the art has to turn to be a picture of the device as it is being held, in degrees
 * clockwise.
 *
 * The framebuffer arrives already rotated — a landscape device sends a landscape picture — so the
 * proportions decide whether the art turns at all, and the orientation word decides which way. The
 * two landscape words are mirror images of each other and the one thing that must not happen is the
 * frame staying upright while the picture inside it lies on its side.
 */
export function artRotation(screen: SimulatorScreen): 0 | 90 | 180 | 270 {
  if (screen.width <= screen.height) return screen.orientation === "portrait_upside_down" ? 180 : 0;
  return screen.orientation === "landscape_right" ? 90 : 270;
}

/** The art and the stream inside it, in CSS pixels, laid into the pane. */
export type ArtLayout = {
  /** The art's box after any rotation — what the pane sizes the frame to. */
  frameWidth: number;
  frameHeight: number;
  /** The art's own box, unrotated, which is what the `<img>` is sized to. */
  artWidth: number;
  artHeight: number;
  /** Degrees clockwise, and the shift that brings the turned picture back over its box. */
  rotation: 0 | 90 | 180 | 270;
  offsetX: number;
  offsetY: number;
  /** The stream, and where it sits inside the frame's box. */
  pictureWidth: number;
  pictureHeight: number;
  pictureLeft: number;
  pictureTop: number;
  /** The device's own display corner, for the clip the picture wears. */
  radius: number;
};

/**
 * Lay the art into the pane, and the stream into the hole in it.
 *
 * The whole DEVICE is scaled to the box, and the stream is FITTED into the measured hole rather than
 * stretched to fill it. `artFor` has already refused the frames whose hole is the wrong shape, so
 * the fit is a rounding difference in practice — but stretching would be a lie about the aspect
 * ratio of what someone is building, which is the one thing a device preview must be honest about.
 */
export function fitDeviceArt(screen: SimulatorScreen, art: DeviceArtFrame, box: Box): ArtLayout | null {
  if (box.width <= 0 || box.height <= 0 || art.width <= 0 || art.height <= 0) return null;
  const rotation = artRotation(screen);
  const turned = rotation === 90 || rotation === 270;
  /* The box the art occupies once turned. A quarter turn swaps the art's own edges; a half turn
     leaves them, which is why 180 is not in here. */
  const boxWidth = turned ? art.height : art.width;
  const boxHeight = turned ? art.width : art.height;
  const k = Math.min(box.width / boxWidth, box.height / boxHeight);

  /* The hole, turned with the art. Each rotation maps the art's own coordinates onto the turned
     box's: 90° sends (x, y) to (H - y, x), 180° to (W - x, H - y), 270° to (y, W - x) — with the
     rectangle's far corner carried through the same map, which is what the subtractions of width
     and height below are. */
  const h = art.screen;
  const hole = rotation === 90
    ? { x: art.height - (h.y + h.height), y: h.x, width: h.height, height: h.width }
    : rotation === 180
      ? { x: art.width - (h.x + h.width), y: art.height - (h.y + h.height), width: h.width, height: h.height }
      : rotation === 270
        ? { x: h.y, y: art.width - (h.x + h.width), width: h.height, height: h.width }
        : { x: h.x, y: h.y, width: h.width, height: h.height };

  const fit = Math.min((hole.width * k) / screen.width, (hole.height * k) / screen.height);
  const pictureWidth = screen.width * fit;
  const pictureHeight = screen.height * fit;
  return {
    frameWidth: boxWidth * k,
    frameHeight: boxHeight * k,
    artWidth: art.width * k,
    artHeight: art.height * k,
    rotation,
    /* Where the turned picture has to be pushed to sit back on its box. Rotation is about the
       element's top-left, so a quarter turn leaves it entirely outside the box on one axis. */
    offsetX: rotation === 90 ? art.height * k : rotation === 180 ? art.width * k : 0,
    offsetY: rotation === 180 ? art.height * k : rotation === 270 ? art.width * k : 0,
    pictureWidth,
    pictureHeight,
    pictureLeft: hole.x * k + (hole.width * k - pictureWidth) / 2,
    pictureTop: hole.y * k + (hole.height * k - pictureHeight) / 2,
    radius: screenRadiusFor(screen, pictureWidth, pictureHeight),
  };
}
