/* Generated by apps/desktop/scripts/fetch-device-frames.mjs — do not edit.
 *
 * The device art in `assets/devices` and where each frame's screen is, in that file's own pixels.
 * Both come from MockUPhone (github.com/oursky/mockuphone.com) at commit 7e570f420ad9;
 * see assets/devices/CREDITS.md for who drew each one. */

import iosPhoneSrc from "../../assets/devices/iphone.png";
import iosTabletSrc from "../../assets/devices/ipad.png";
import androidPhoneSrc from "../../assets/devices/android-phone.png";

export type DeviceArt = {
  /** The device this frame stands in for. */
  name: string;
  /** The art's own pixel size. */
  width: number;
  height: number;
  /** The screen hole, in those same pixels. */
  screen: { x: number; y: number; width: number; height: number };
};

export const DEVICE_ART = {
  iosPhone: { src: iosPhoneSrc, name: "iPhone 15 Pro", width: 1218, height: 2400,
    screen: { x: 103, y: 103, width: 1012, height: 2194 } },
  iosTablet: { src: iosTabletSrc, name: "iPad Pro 11-inch", width: 1738, height: 2400,
    screen: { x: 101, y: 101, width: 1534, height: 2196 } },
  androidPhone: { src: androidPhoneSrc, name: "Google Pixel 8", width: 978, height: 2100,
    screen: { x: 33, y: 49, width: 902, height: 2002 } },
} satisfies Record<string, DeviceArt & { src: string }>;

export type DeviceArtKey = keyof typeof DEVICE_ART;
