import type { SealedEggPack } from "@realm/contracts";

/**
 * The sealed friend packs. GENERATED by `tools/seal-egg-packs.mjs` — do not edit by hand.
 *
 * Every one of these is a group of real people's names and in-jokes, encrypted under a word that
 * group already knows. Nothing here is readable from the repository, which is the point: Realm is
 * open source and these are not Realm's jokes to publish. See `egg-pack.ts` for what the sealing
 * does and does not promise.
 *
 * The ids are opaque and stable. A pack's id is what a remembered passphrase is stored against, so
 * renaming one asks its group to type their word again.
 */
export const EGG_PACKS: readonly SealedEggPack[] = [
  {
    "id": "p1",
    "v": 1,
    "salt": "8Z3LALxkSCsvJNBkQU5prA==",
    "iv": "dJpqbZx0U1Xu2vEE",
    "ct": "WlaCh6z59auL+138z+2RK2JLjLaGLo1feqTHwyCbPpBAROIdgaRC6PhG9szKbXHK7SvVuiS35zZcFkH9X6LqbEI6lZm0FUJNFX8jlcn2MW9Kb2sa+JLuJ1DE6fVd8V77OhM5QcDa/TLfFkyWpTX6d3Cx4LXjXaHP7FUtEf+gAv4k2E2XTElr2Dn1hqPN8dzAGXgMqCdKjKMksfe2GuTKabum63sIE7byVBLT0Q9guulOhBvJyJY+HHgPKfCiClvEpXtcX1w+2YUfwJWJnHbHrEVYG7NxBKRfDOjT5eeTRgtoutrYFzyHZacVfqUPyNSPO2XA8lp+TewGksSo9Anb72rfON8WxwKt1JgpCrRTIdInYnRhX1qx45MoCi8R2ToEG4tpOaeoeBam8mstyaLHXtpQ1KSkawd7DjxhRSKcCluDk/G+IWcmPch2QHACBWdpxfwbPpvxN1hjBLmRlNEuoAUMM0HW4ZXp58H8xTY1YO00DTs="
  },
  {
    "id": "p2",
    "v": 1,
    "salt": "tFgysrSMP9Okg9Uc+Yc75g==",
    "iv": "Q4vqoo0f7xjB/wzg",
    "ct": "Uwchp9MeLXmjuAV9fG+XEWJDjzsZt4i48D+0rSex7LPyqG8SZ42iv+jXQDqXCqMtYRSSND72fSdmVjWFZbd06OItl2Za22iDrt++EQjObheOb7F7iNfC4TPen48ANuwJVuu5Kjr5VskZ7FtXx1Anmp/rLld+lfkLtPdIRJinPg6IR4q39nSxudMtScaxQ5ChPHpJYB+uS9uGB964AUjSeydTjGuaEK0lPLNVEN/SLE2jfmoV/NIz/swQicgI4Yfq86TbEkhLuZShPRYmWbyyMSer4oaMru1b8WTvHht6VW4UJWeom6y0Ylmj7hpknGcggl135w3cnSV5ZcfdDZajBCB8A1mTxpuQR4oengR7JW/r2JhG/tiNGgv5+JvrLwQ2rxr5yPh17tewa32U4wff62dtkdplbshM36QiEft+mA+xHhfI3EssTQgHDYYo8drvxJjO0e5WLtm/IFXz4LM18DCW/jlkL7KTGOOuH3yJlAIIXN56YmW9SmrYCDPlcaNVJ/PqiA3Ge/tHKGbASH+ML2PVjv2dpkg1fSgsliXJ1CKBn45E3YG/rCtdgC/GI+3Z5Y5Gqy2j3QpyvKIliT4r8/Cf3ZJD4ap4ZNoSTZbX/koLBfoHVQNK19ehNd5ybab9nlvMz7AKjac+H/oLLY4rSAVJShilVbv+wmnzmAb2HKs9Um/cn3r5dkIFmai/hHpP9YBAO/omHoxqJfrHVogN1iGQ"
  },
  {
    "id": "p3",
    "v": 1,
    "salt": "2SfE7ISAsH6Qh1pNoSNqVg==",
    "iv": "opfZQFJXIg3h+tjD",
    "ct": "SXBY2RcxeuUsf8uYfAxyOY93cfmky3v5T0VkXWtovKiLNmb+G/Vfu1BHtKjDKNp7/SHMaZ+Q08KQ0wxIaFbafdQAhOMmtoEBy5UeXi5TOozK20QNn568JN5q4MscTJUDMN+9vNGn3U8Hz5xC8nIkNN+ub70+QEo/7ZpOBf28NDewps3DUGZ+tnL7wJAaJ1gn+u4RZetobh44iTj09tvcghOZ2DsbWkV75j6bUkDiELuKBd8AK4zQgwoQglrg3D01/NS8l2w6b7bOsPzt5V6fornqOm2fW4CwBcQDRSYprXu7kTOtL9vMFIVKw/IxDFjmQe0T0OsYSwrq7s3i7V8FL3YlhgviBm3z1/22lZ4YODO6s34/l/0GPEiyOBQlqdDSAEGm4nmItFt67un2B6od7BQnZZu6iiC/0bkhrrGyZc6J8IVTrv2fQNPI/uh7ko6B1EfE02SncAoXJLhkjI8iREZH8+p+zEBDla/JJEmRvj8vsELsuxuN53j5xFK5FpIEWj50eWZaiwWUFsergoi3hOheklyt4ud9FLCH321iIOPD+ZWDqGNY4arwjg0qSy0lvwSHk6tS7N8TKAGnSqv0mHSBShHEZSSuzQqu8xBmqhqvZCwVTNxTlef2RhxdZUY6fJUvqP50Y7rRSDDaUwKoEySKLjlE7gEqCyzfzLjisEw7NlihNFHykO2pl+kuva5DG8pl8Rxl+Hig51djP2AAdqad5js4U5J5RY+BKe1XFYzpOVZ0Qd/HO35QD7ulWY03wEa3I3LB24sOivXZdF/chaUh6AD7ycmesYVXYJE9mWAORBQ910p+SH+3zBqi0kfUqTdNg+B9U3WaYiiXy8B2cR7YOGx9WzglVaJf2xtshlhQ6SqJgztJqgbn2d2IlaJP80YdjY7lzLEaJj26Pqecj+i9nXOnrSqtTj2L6kVfWefQxg6BMwza1CPN8lBKsR6/eldhU12erfWYQ6Nyi0nuSej1Ttc="
  },
  {
    "id": "p4",
    "v": 1,
    "salt": "dPeyNOOk/K2usvOVDAXLOw==",
    "iv": "x+uMp8GDVVwfI/+2",
    "ct": "1Z3RwkuoqT3G3mQTmeABCMutVOoYJD4nRrtU64yzhxechCqUaNUtE1TrL332sQ2y45jdLJGItINVu9rrWmJm20usTsDhUsAFyASm4RCrr8lGCskI2lA9k9pQ2dZf+MPLtM86uthI5oNmeYcV8b4ygHKnG1e1UhZmKKV2Z7n7qACniaZzlx1/9SSUxGDUglJZFLgXoXP6tUdf+cK+md88jbX7hlV5ual3dLfHZPVH2XxvCh7gSn4Jg/hm0/lMnayqL2LH6sG+tBH6aCC+1VTjq07SDSBLTMPH+qIi8A02mLLuOWpHPwUoNe+chKk6POvXXKRqvn/gH+s0tRkN0XbTeO0apBn/Gre7f+LFQ27RvBB0hQle4/ZAXQHTSpJ2RX8l4CkLCMz6N4ouXgZlEshYmUJacy2kEru8S+xYE1CjH6Nzqo0SKfyibc5J0nBC6Na+rPtHa+kNVFF1RqCfGxOX/Ml3yKS23jDu7+VbCiO6RzvP9Oj+x9gsBe7JLEmD5UlEndIMSI42KuDu"
  },
  {
    "id": "p5",
    "v": 1,
    "salt": "tmj4GtBjW9i+astgwVIvCg==",
    "iv": "2CU8uDfn+9pZS48g",
    "ct": "gH00tu7W5S8gmSEnWlmS+XcjXENSnJP7AeCyW3oWV3r9CD7bZiIKJsd7s5B6cRxS21WhYeVB1WTiSLNo58hFMQcS3J20wFGHaQGQ6seIenUV7yMBLtQ0QmBNcNHAOpP72wg2a7WxAkwn/KsFLsUPU1oLnaNmvAkVNlHPg7DBx1iR6uPECKBCYbPBgA8F+/RhoqgelU5oaKjmrHEpAHA3OW+J3qrtOswqurU5MhBCqQx6lRptKxxu2ZaYsUSTWk5Wo8p+cgdG7fObX0TdFfcKfj09dFAlM66yFAr9dVT2ZS+hE1bpG+BoDYZmRt+Z1UXQU5HFSpX1mXUPYEVu15zOWL48QJu8bwWYTsb+QZ4bwtRjmRNV+eQTDgZOD/hOngqfGNTDcDrNCTZJRmjEMWrtbm93RukuvC+oUpqyRe+X9VHPTi9VEPhFxNRcScXWz93IhOQamvEBhi19KsJpNrdlp4om2TBiCDTGnDwMz4AM+8HzUjSDOlhe41t+N5zGsTYCsFqjRM0v0OEPLXseRz50ESS4ZH8y2FoOUgeu7fToXp5Uj2yVSToykWg8J15p7g=="
  },
  {
    "id": "p6",
    "v": 1,
    "salt": "k+l+0lg9tQpnAVrTqz47yA==",
    "iv": "AelD4etk/x1GtIla",
    "ct": "TT6XapWHUwwNCFMz/dYVougNAaYv3JVkDnbpo620O3xamn/ywOmrVhYsOmxKmHlj1HYY+HjXHgVqsURKg4bjE6rPmwZX3ERuPBBHkh8ztVoTzgvmjKCl8xej+Jz5ZSmEOmAUFkZ2DX1wGIcvGulmRQ8LSolWlp3gxxFmO5A7nHvNn1XBxAPcs9cpS8ExL/oV2LcFoO7EbSDqfjpbraO37Lo9AQJBHZb+5gCNeMeOfQqh/ULxYLb6pcq/QE78dzX99lX7AirlN5iwoe1/PuljfLU0EGAkuQ04e84/0qOywGSI/WGHJ9tW+d9e3L4KplC652LEgRI0Zgsv4T/UyUqa3fKCYhH6NfVAukkIjOdE8MXWfKLpmA/gLmf8AznoJhGOvpBbeVq80LoGyDpKQhoIj7NCS9oFNumEDug6nDt3lh0/0D17llENYg=="
  },
  {
    "id": "p7",
    "v": 1,
    "salt": "zSTbbsZnUYDtjnVTsS82rg==",
    "iv": "gjrG2hrc+COrHKvz",
    "ct": "FhjGOuHDO2IjG9HPOPPYiGMt4SMOS7AvTEPyZgE18xVfZJvS/oC+Zf1pcBJhSs8c065QXyj94HdH2FblpEacd26CSjjJ1c/ebxlFB1WWw+rODBb/LqqjjM/6CYzbYzbLWeAWL8+jl/qK2sFF3Vj3igF2MhVEYMsVNZRrRKhRd0tsutVRkzTmUfxhNx8TAB2x1znzZXiiBlsjbG8/pQDNUrBIP1X8HjLTR0ZDsQ4/MUm0ZtulrRlW/lbLSQceLE2lcVKzAI45V3mtHL3NtZ4A85P7UEqHl+u8KxOlw0s1VEUKeyqy35PR0zNJpRCe+GhUGbrWy/1bqRw4hWdnUPXXMzLk15TzVWriAhDzhjX5ENbtUAd48gck8zZstpolUiOGoWnnD/Ek4kluXZwp26aChDPIpCazhUQS21dGQ+fve4xxwudJujJbxtS6znqq/SVrcecCbGkdUrjFBKhXUodmq20LCbTQhEwNg51F/QIEggUtzvMEExk9MHd3xy3haiAA2w6evRDiZFgD2d/tzm/+nzOFNrT8xUE="
  },
  {
    "id": "p8",
    "v": 1,
    "salt": "uJpxSBKFUov4UmXotNBW2g==",
    "iv": "bk7pA5ieHqLbfLcD",
    "ct": "BajVjrkkeGLKze/8bSfsj9R4aLhrLf6cj8WX8qBsTal8pAEeNj7DoMZ4t00UE9VCQ2IKIKv/8rTZyqC+Qt4/kbKK93owUSAdSBtaj6xt3jWX00dld15GtRCP9+evrX1AhMxe9emokOapRO/+5Iqi7v2jc4YrQD7q+UUbKvZGhUA3lyv4NzZYW2dqI/scucKjXG1wicw5GUSF7f8lRAe7PS1zrZrwX3+yT136jnMXQ+yPkNSAWPE0FMkZ4maYdz0Igo5yt4Jmwyxmsh4/aZ6UMNaPHmUjivJDlDgGA9JzrULwmc9Tr+GfHM7EJeqUGqHJsj+Y/wA7tXnyuPVaUcmL7+VvwsW9byDla10ZDe2GwrcxQFW3rxDNm7M1P9yk0HYIkI6NtFrl0BchZBxheTBi79CytGzrenkPk0jVpye067jO5SysN40TLSujHZJSzy7/bVr0Rf9YSDo451lXaRmoUfgBtHuaL3wYme7IERKu4GUHIyTcFM+TmoFQEnpecmpJPI9wkU02Lrbzcc8qx5ASAd2iJuuEnUTkwG/x5H8jV4ZL7tuB5QgrNFoqrFt37s1BJG51OUR8xQpnMpLGnHXJD3q58jGLF44YCQsqXQaavr7Tcpgl9TaakVKV2TNl09Vfx1JOSDqR3iyP/Y+mpOdxr/eV43vqdB1Vuga28ee0hCQ05C98PUOvY/3sH1xnVnKQMf+hJ6vMCPoXjVUEiKQXpjzm1SOyTKhrNvtIwfDnMFj569eu1PnFbkmczd0crmr/"
  }
];
