import { play } from "cuelume";
import { rpc } from "../rpc/client";
import { getTerminalHub } from "../panes/terminal-hub";
import type { Api } from "./store";

/** The real Api: realm-server over WebSocket plus the Electron/xterm platform seams.
 *  Kept out of store.ts so the store (and its tests) never pull in xterm or the rpc singleton. */
export const liveApi = (): Api => ({
  listProfiles: () => rpc().call("profiles.list", {}),
  createProfile: (name) => rpc().call("profiles.create", { name }),
  listSpaces: () => rpc().call("spaces.list", {}),
  listItems: (spaceId) => rpc().call("items.list", { spaceId }),
  listAllItems: () => rpc().call("items.listAll", {}),
  search: (profileId, query) => rpc().call("search.query", { profileId, query }),
  libraryArtifacts: (q) => rpc().call("library.artifacts", q),
  listProjects: (spaceId) => rpc().call("projects.list", { spaceId }),
  listEnvironments: (spaceId) => rpc().call("environments.list", { spaceId }),
  createWorktree: (spaceId, title) => rpc().call("environments.createWorktree", { spaceId, title }),
  createSpace: (input) => rpc().call("spaces.create", input),
  updateSpace: (input) => rpc().call("spaces.update", input),
  reorderSpaces: async (ids) => { await rpc().call("spaces.reorder", { ids }); },
  deleteSpace: async (id) => { await rpc().call("spaces.delete", { id }); },
  createProject: (spaceId, name, rootPath) => rpc().call("projects.create", { spaceId, name, rootPath }),
  setLayout: (id, layout) => rpc().call("spaces.setLayout", { id, layout }),
  setGroups: (id, groups, activeItemId) => rpc().call("spaces.setGroups", { id, groups, activeItemId }),
  createTerminal: (spaceId) => rpc().call("terminals.create", { spaceId }),
  createBrowser: (spaceId) => rpc().call("browsers.create", { spaceId }),
  createMachine: (spaceId, name) => rpc().call("machines.create", { spaceId, name }),
  createSimulator: (spaceId, name) => rpc().call("simulators.create", { spaceId, name, udid: null }),
  goalGet: (sessionId) => rpc().call("goals.get", { sessionId }),
  eggsList: () => rpc().call("eggs.list", {}),
  eggsUnlock: (passphrase) => rpc().call("eggs.unlock", { passphrase }),
  eggsForget: async (id) => { await rpc().call("eggs.forget", { id }); },
  goalStart: (sessionId, objective, tokenBudget) => rpc().call("goals.start", { sessionId, objective, tokenBudget }),
  goalSet: (sessionId, status, note) => rpc().call("goals.set", { sessionId, status, note }),
  goalResume: (sessionId) => rpc().call("goals.resume", { sessionId }),
  goalClear: async (sessionId) => { await rpc().call("goals.clear", { sessionId }); },
  createDocuments: (spaceId, environmentId) => rpc().call("documents.create", environmentId ? { spaceId, environmentId } : { spaceId }),
  getDocuments: (documentsId) => rpc().call("documents.get", { documentsId }),
  setDocumentTabs: (documentsId, openPaths, activePath) => rpc().call("documents.setTabs", { documentsId, openPaths, activePath }),
  detachDocuments: async (documentsId) => { await rpc().call("documents.detach", { documentsId }); },
  listDocumentEntries: async (documentsId, dir) => (await rpc().call("documents.list", { documentsId, dir })).entries,
  readDocument: (documentsId, path) => rpc().call("documents.read", { documentsId, path }),
  writeDocument: (documentsId, path, text, baseHash) => rpc().call("documents.write", { documentsId, path, text, baseHash }),
  createDocumentFile: (documentsId, path, kind, title) => rpc().call("documents.createFile", { documentsId, path, kind, title }),
  renameDocumentFile: (documentsId, from, to) => rpc().call("documents.renameFile", { documentsId, from, to }),
  previewInfo: () => rpc().call("documents.previewInfo", {}),
  openDocumentPath: (spaceId, path, environmentId) => rpc().call("documents.openPath", environmentId ? { spaceId, path, environmentId } : { spaceId, path }),
  readGuideProgress: (documentsId, path) => rpc().call("documents.progressRead", { documentsId, path }),
  recordGuideAttempt: (documentsId, path, topic, correct, total) => rpc().call("documents.progressRecord", { documentsId, path, topic, correct, total }),
  startLecture: (spaceId, title) => rpc().call("lectures.start", { spaceId, title }),
  listLectures: async (spaceId) => (await rpc().call("lectures.list", { spaceId })).lectures,
  plynnList: () => rpc().call("plynn.list", {}),
  plynnImport: (spaceId, files) => rpc().call("plynn.import", { spaceId, files }),
  updateItem: (input) => rpc().call("items.update", input),
  deleteItem: async (id) => { await rpc().call("items.delete", { id }); },
  getSetting: async (key) => (await rpc().call("settings.get", { key })).value,
  setSetting: async (key, value) => { await rpc().call("settings.set", { key, value }); },
  listComputerAllowedApps: async (spaceId) => (await rpc().call("computer.allowedApps.list", { spaceId })).apps,
  setComputerAllowedApps: async (spaceId, apps) => (await rpc().call("computer.allowedApps.set", { spaceId, apps })).apps,
  systemInfo: async () => { const i = await rpc().call("system.info", {}); return { machineName: i.machineName, userName: i.userName, detachedSince: i.detachedSince }; },
  pickFolder: () => window.realm.pickFolder(),
  pickFiles: () => window.realm.pickFiles(),
  listIconAssets: (profileId) => rpc().call("iconAssets.list", { profileId }),
  generateIconAsset: (profileId, prompt) => rpc().call("iconAssets.generate", { profileId, prompt }),
  describePaths: (paths) => window.realm.describePaths(paths),
  pickIconImage: () => window.realm.pickIconImage(),
  compressIconImage: (path) => window.realm.compressIconImage(path),
  uploadIconAsset: (profileId, path) => rpc().call("iconAssets.upload", { profileId, path }),
  deleteIconAsset: async (id) => { await rpc().call("iconAssets.delete", { id }); },
  pathForFile: (file) => window.realm.pathForFile(file),
  saveTempAttachment: (name, mime, bytes) => window.realm.saveTempAttachment(name, mime, bytes),
  disposeTerminal: (terminalId) => getTerminalHub().dispose(terminalId),
  destroyBrowserView: (browserId) => { void window.realm.browser.destroy(browserId); },
  listSessions: (spaceId) => rpc().call("sessions.list", { spaceId }),
  listAllSessions: (profileId = null) => rpc().call("sessions.listAll", { profileId }),
  getSession: (id) => rpc().call("sessions.get", { id }),
  /* The wire's `itemId` is nullable because `unlisted` exists; a plain create never asks for one, so
     the non-null it always returns is asserted here rather than at four call sites that cannot get
     null. `createUnlistedSession` is the one that can, and it does not read `itemId` at all. */
  createSession: async (input) => {
    const { session, itemId } = await rpc().call("sessions.create", input);
    return { session, itemId: itemId! };
  },
  createUnlistedSession: (input) => rpc().call("sessions.create", { ...input, unlisted: true }),
  deleteSession: async (id) => { await rpc().call("sessions.delete", { id }); },
  forkSession: (checkpointId, agentKind) => rpc().call("sessions.fork", { checkpointId, ...(agentKind ? { agentKind } : {}) }),
  listSkills: (spaceId) => rpc().call("skills.list", { spaceId }),
  projectGrep: (cwd, query, limit) => rpc().call("project.grep", { cwd, query, ...(limit === undefined ? {} : { limit }) }),
  projectFiles: (cwd, query, limit) => rpc().call("project.files", { cwd, query, ...(limit === undefined ? {} : { limit }) }),
  listScripts: (spaceId) => rpc().call("scripts.list", { spaceId }),
  runScript: (spaceId, commandId) => rpc().call("scripts.run", { spaceId, commandId }),
  saveScript: (spaceId, script) => rpc().call("scripts.save", { spaceId, script }),
  removeScript: async (spaceId, id) => { await rpc().call("scripts.remove", { spaceId, id }); },
  reorderScripts: (spaceId, ids) => rpc().call("scripts.reorder", { spaceId, ids }),
  getSandbox: (spaceId) => rpc().call("sandbox.get", { spaceId }),
  setSandbox: (spaceId, prefs) => rpc().call("sandbox.set", { spaceId, prefs }),
  getKeybindings: () => rpc().call("keybindings.get", {}),
  writeKeybindings: (rules) => rpc().call("keybindings.set", { rules }),
  resetKeybindings: () => rpc().call("keybindings.reset", {}),
  listCommands: (spaceId) => rpc().call("commands.list", { spaceId }),
  expandCommand: (spaceId, name, args) => rpc().call("commands.expand", { spaceId, name, args }),
  listThemes: () => rpc().call("themes.list", {}),
  pickThemeFile: () => window.realm.pickThemeFile(),
  importTheme: (path) => rpc().call("themes.import", { path }),
  removeTheme: async (id) => { await rpc().call("themes.remove", { id }); },
  listInstalledFonts: () => rpc().call("fonts.installed", {}),
  fontCatalog: () => rpc().call("fonts.catalog", {}),
  installFont: (family) => rpc().call("fonts.install", { family }),
  removeFont: async (family) => { await rpc().call("fonts.remove", { family }); },
  fontFaces: (family) => rpc().call("fonts.faces", { family }),
  listSkillSources: (spaceId) => rpc().call("skills.sources", { spaceId }),
  readSkill: (spaceId, id) => rpc().call("skills.read", { spaceId, id }),
  readSkillFile: (spaceId, id, rel) => rpc().call("skills.readFile", { spaceId, id, rel }),
  addSkillScanRoot: async (path) => { await rpc().call("skills.addScanRoot", { path }); },
  removeSkillScanRoot: async (path) => { await rpc().call("skills.removeScanRoot", { path }); },
  setSkillEnabled: async (spaceId, id, enabled) => { await rpc().call("skills.setEnabled", { spaceId, id, enabled }); },
  promoteSkill: async (spaceId, id) => { await rpc().call("skills.promote", { spaceId, id }); },
  demoteSkill: async (spaceId, id) => { await rpc().call("skills.demote", { spaceId, id }); },
  testMcpServer: (id) => rpc().call("mcp.test", { id }),
  getMemory: (spaceId) => rpc().call("memory.get", { spaceId }),
  setMemory: (spaceId, doc) => rpc().call("memory.set", { spaceId, doc }),
  setAgentsFile: (spaceId, enabled) => rpc().call("memory.setAgentsFile", { spaceId, enabled }),
  memorySources: (sessionId) => rpc().call("memory.sources", { sessionId }),
  // `elements` is omitted rather than sent empty: a message with no element chips must put exactly
  // the bytes on this wire that it did before chips existed.
  sendMessage: async (id, text, attachments, mentions, elements, delivery, sessionRefs) => {
    await rpc().call("sessions.send", { id, text, attachments, mentions, ...(elements?.length ? { elements } : {}), ...(sessionRefs?.length ? { sessionRefs } : {}), ...(delivery && delivery !== "auto" ? { delivery } : {}) });
  },
  interruptSession: async (id) => { await rpc().call("sessions.interrupt", { id }); },
  dequeuePrompt: async (id, queuedId) => { await rpc().call("sessions.dequeue", { id, queuedId }); },
  releaseQueuedPrompt: async (id, queuedId) => { await rpc().call("sessions.releaseQueued", { id, queuedId }); },
  sessionQueue: async (id) => (await rpc().call("sessions.queued", { id })).queued,
  planLimits: async () => (await rpc().call("limits.get", {})).limits,
  recordFeedback: async (id, messageId, rating) => { await rpc().call("sessions.recordFeedback", { id, messageId, rating }); },
  respondPermission: async (id, requestId, decision, answers) => { await rpc().call("sessions.respondPermission", { id, requestId, decision, ...(answers ? { answers } : {}) }); },
  setSessionOptions: (id, o) => rpc().call("sessions.setOptions", { id, ...o }),
  setSessionAgent: (id, agentKind) => rpc().call("sessions.setAgent", { id, agentKind }),
  failoverGet: (spaceId) => rpc().call("failover.get", { spaceId }),
  failoverSet: (spaceId, policy) => rpc().call("failover.set", { spaceId, policy }),
  setSessionEnvironment: (id, environmentId) => rpc().call("sessions.setEnvironment", { id, environmentId }),
  moveSessionToSpace: (id, spaceId) => rpc().call("sessions.moveToSpace", { id, spaceId }),
  sessionEvents: (id, afterSeq, limit) => rpc().call("sessions.events", { id, afterSeq, limit }),
  openSessionTerminal: (id) => rpc().call("sessions.openTerminal", { id }),
  writeTerminal: async (terminalId, data) => { await rpc().call("terminals.write", { terminalId, data }); },
  prefillTerminal: async (terminalId, command) => { await rpc().call("terminals.prefill", { terminalId, command }); },
  probeAgents: (force) => rpc().call("agents.probe", { force }),
  cliStatus: async (force) => (await rpc().call("cli.status", { force })).rows,
  runCli: (kind, action) => rpc().call("cli.run", { kind, action }),
  modelCatalog: async (force) => (await rpc().call("models.catalog", { force })).rows,
  usageSummary: (p) => rpc().call("usage.summary", p),
  usageActiveDays: (p) => rpc().call("usage.activeDays", p),
  setUsageBudget: (budget) => rpc().call("usage.setBudget", budget),
  importScan: () => rpc().call("import.scan", {}),
  importApply: (selection) => rpc().call("import.apply", selection),
  tccProbe: () => window.realm.permissions.probe(),
  credentialList: () => window.realm.credentials.list(),
  credentialStatus: () => window.realm.credentials.status(),
  credentialAdd: (input) => window.realm.credentials.add(input),
  credentialRemove: (id) => window.realm.credentials.remove(id),
  credentialSetPresenceTtl: (ms) => window.realm.credentials.setPresenceTtl(ms),
  openTccPane: (pane) => window.realm.permissions.openSettings(pane),
  macAccessStatus: () => window.realm.macAccess.status(),
  macAccessGrant: (id) => window.realm.macAccess.grant(id),
  macAccessOpenSettings: (id) => window.realm.macAccess.openSettings(id),
  macAppIcon: (id) => window.realm.macAccess.appIcon(id),
  macAccessRevealApp: () => window.realm.macAccess.revealApp(),
  computerAccessStatus: () => window.realm.computerAccess.status(),
  computerAccessRequest: (id) => window.realm.computerAccess.request(id),
  computerAccessOpenSettings: (id) => window.realm.computerAccess.openSettings(id),
  updateStatus: () => window.realm.updates.status(),
  checkUpdates: () => window.realm.updates.check(),
  installUpdate: () => window.realm.updates.install(),
  showDesktopNotification: (input) => window.realm.notify.show(input),
  // cuelume builds nothing until the first `play`, so importing it costs no AudioContext. It then
  // refuses to sound until the document has had a user gesture, checking
  // `navigator.userActivation.hasBeenActive` itself — Electron leaves a context `running` without
  // one, so that flag is the only gate, and any click or keypress flips it for the document's life.
  // A cue arriving before the user has ever touched this window is dropped; its toast still shows.
  playCue: (cue, volume) => { play(cue, { volume }); },
  resyncTerminals: () => { getTerminalHub().resyncAll(); },
  setBadgeCount: (count) => window.realm.notify.badge(count),
  gitInfo: (cwd) => rpc().call("workspace.gitInfo", { cwd }),
  diff: (cwd) => rpc().call("workspace.diff", { cwd }),
  fileDiff: (cwd, path, staged) => rpc().call("workspace.fileDiff", { cwd, path, staged }),
  stagePaths: async (cwd, paths) => { await rpc().call("workspace.stage", { cwd, paths }); },
  unstagePaths: async (cwd, paths) => { await rpc().call("workspace.unstage", { cwd, paths }); },
  ship: (input) => rpc().call("workspace.ship", input),
  listShips: (spaceId, cursor = null, limit) => rpc().call("ships.list", { spaceId, cursor, ...(limit !== undefined ? { limit } : {}) }),
  createItem: (spaceId, kind, title, refId) => rpc().call("items.create", { spaceId, kind, title, refId }),
  worktreeStatus: (id) => rpc().call("environments.worktreeStatus", { id }),
  removeWorktree: async (id, acknowledge) => { await rpc().call("environments.removeWorktree", { id, acknowledge }); },
  listCheckpoints: (environmentId, sessionId) => rpc().call("checkpoints.list", { environmentId, sessionId }),
  captureCheckpoint: (environmentId, sessionId) => rpc().call("checkpoints.capture", { environmentId, sessionId }),
  previewCheckpoint: (id) => rpc().call("checkpoints.preview", { id }),
  restoreCheckpoint: (id, acknowledge) => rpc().call("checkpoints.restore", { id, acknowledge }),
  listMcpServers: (spaceId) => rpc().call("mcp.list", { spaceId }),
  addMcpServer: (input) => rpc().call("mcp.add", input),
  updateMcpServer: (input) => rpc().call("mcp.update", input),
  removeMcpServer: async (id) => { await rpc().call("mcp.remove", { id }); },
  setMcpEnabled: async (spaceId, id, enabled) => { await rpc().call("mcp.setEnabled", { spaceId, id, enabled }); },
  promoteMcpServer: async (spaceId, id) => { await rpc().call("mcp.promote", { spaceId, id }); },
  demoteMcpServer: async (spaceId, id) => { await rpc().call("mcp.demote", { spaceId, id }); },
  listMcpProviders: async (spaceId) => (await rpc().call("mcp.providers.list", { spaceId })).providers,
  setMcpProviderEnabled: async (spaceId, name, enabled) => { await rpc().call("mcp.setProviderEnabled", { spaceId, name, enabled }); },
  getProfileMemory: (profileId) => rpc().call("memory.getProfile", { profileId }),
  setProfileMemory: (profileId, doc) => rpc().call("memory.setProfile", { profileId, doc }),
  setProfileDocEnabled: (spaceId, enabled) => rpc().call("memory.setProfileDocEnabled", { spaceId, enabled }),
  mcpToolsList: (id) => rpc().call("mcp.tools.list", { id }),
  setMcpAllowedTools: async (spaceId, id, tools) => { await rpc().call("mcp.setAllowedTools", { spaceId, id, tools }); },
  startMcpOauth: (id) => rpc().call("mcp.oauth.start", { id }),
  setMcpOauthClient: async (id, client) => { await rpc().call("mcp.oauth.setClient", { id, ...client }); },
  disconnectMcpOauth: async (id) => { await rpc().call("mcp.oauth.disconnect", { id }); },
  retryMcpServer: async (id) => { await rpc().call("mcp.retry", { id }); },
  mcpCallsList: (params) => rpc().call("mcp.calls.list", params),
  listSchedules: (spaceId) => rpc().call("schedules.list", { spaceId }),
  createSchedule: (input) => rpc().call("schedules.create", input),
  updateSchedule: (input) => rpc().call("schedules.update", input),
  deleteSchedule: (id) => rpc().call("schedules.delete", { id }),
  runScheduleNow: (id) => rpc().call("schedules.runNow", { id }),
  listRuns: (spaceId, states, cursor = null, limit) => rpc().call("runs.list", { spaceId, ...(states ? { states } : {}), cursor, ...(limit !== undefined ? { limit } : {}) }),
  createRun: ({ spaceId, goal, title }) => rpc().call("runs.create", { spaceId, goal, ...(title ? { title } : {}) }),
  getRun: (id) => rpc().call("runs.get", { id }),
  cancelRun: (id) => rpc().call("runs.cancel", { id }),
  retryRun: (id) => rpc().call("runs.retry", { id }),
  approveRun: (id, approved, note) => rpc().call("runs.approve", { id, approved, note }),
  listNotifications: (cursor, limit) => rpc().call("notifications.list", { cursor, ...(limit !== undefined ? { limit } : {}) }),
  markNotificationsRead: (input) => rpc().call("notifications.markRead", input),
  markSessionSeen: async (id, seq) => { await rpc().call("sessions.markSeen", { id, seq }); },
  requestReview: (environmentId) => rpc().call("review.request", { environmentId }),
  getReview: (environmentId) => rpc().call("review.get", { environmentId }),
  dismissReview: async (environmentId) => { await rpc().call("review.dismiss", { environmentId }); },
  listDelegatedRuns: async (sessionId) => (await rpc().call("delegation.running", { sessionId })).running,
});
