#!/usr/bin/env node
/**
 * `pnpm release` (Plan 15 W2) — release discipline, LOCAL ONLY. In order:
 *
 *   1. refuses a dirty tree or an already-existing tag,
 *   2. bumps apps/desktop/package.json's version (patch by default; --minor / --major),
 *   3. prepends a changelog stub to CHANGELOG.md from merged PR titles since the last tag —
 *      `gh pr list` when it answers, else the squash-merge "(#N)" subjects in git log, else
 *      (fully offline / no PRs) plain commit subjects. The stub is a STUB: a human edits it,
 *   4. builds dmg + zip + latest-mac.yml through the normal `pnpm dist` (which pins
 *      `--publish never` — this script cannot publish even by accident),
 *   5. commits the bump + stub and creates the vX.Y.Z tag, locally.
 *
 * It never pushes, never talks to a release API, and ends by printing exactly what a human does
 * next. `--dry-run` prints the whole plan (bump, entries, provenance) and touches nothing.
 */
import { execFileSync, spawn } from "node:child_process";
import { closeSync, existsSync, mkdtempSync, openSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// ---------- pure logic (mutation-grade tested in release.test.ts) ----------

export function parseReleaseArgs(argv) {
  const known = new Set(["--minor", "--major", "--dry-run"]);
  const unknown = argv.filter((a) => !known.has(a));
  if (unknown.length) throw new Error(`unknown flag ${unknown[0]} — pnpm release [--minor|--major] [--dry-run]`);
  const minor = argv.includes("--minor");
  const major = argv.includes("--major");
  if (minor && major) throw new Error("--minor and --major are exclusive — pick one");
  return { kind: major ? "major" : minor ? "minor" : "patch", dryRun: argv.includes("--dry-run") };
}

export function bumpVersion(version, kind) {
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(version);
  if (!m) throw new Error(`cannot bump non-semver version "${version}"`);
  const [major, minor, patch] = [Number(m[1]), Number(m[2]), Number(m[3])];
  if (kind === "major") return `${major + 1}.0.0`;
  if (kind === "minor") return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

/** Surgical version edit — a targeted replace, never JSON.stringify, so the file's hand-kept
 *  formatting (comment keys, ordering) survives byte-for-byte. Refuses ambiguity. */
export function bumpPackageJsonText(text, next) {
  const hits = text.match(/"version"\s*:/g) ?? [];
  if (hits.length !== 1) throw new Error(`expected exactly one "version" key, found ${hits.length}`);
  return text.replace(/("version"\s*:\s*")[^"]+(")/, `$1${next}$2`);
}

/** A squash-merged PR's subject — `Title (#N)` — becomes a changelog entry; anything else doesn't. */
export function prEntryFromSubject(subject) {
  const m = /^(.+)\s\(#(\d+)\)$/.exec(subject.trim());
  return m ? `${m[1]} (#${m[2]})` : null;
}

/** The degradation ladder's git half: PR-shaped subjects when any exist, else plain commit
 *  subjects (merge-commit noise dropped) — offline never produces an empty lie, only humbler truth. */
export function changelogEntries(subjects) {
  const pr = subjects.map(prEntryFromSubject).filter((e) => e !== null);
  if (pr.length) return { source: "pr-titles", entries: pr };
  const plain = subjects.map((s) => s.trim()).filter((s) => s && !/^Merge (branch|pull request|remote-tracking)/.test(s));
  return { source: "commit-subjects", entries: plain };
}

/** `gh pr list --json number,title,mergedAt` → entries merged strictly after sinceIso (all, when
 *  there is no previous tag), newest first. Malformed rows are dropped, not crashed on. */
export function entriesFromGh(rows, sinceIso) {
  if (!Array.isArray(rows)) return [];
  return rows
    .filter((p) => p && typeof p.title === "string" && typeof p.number === "number" && typeof p.mergedAt === "string")
    .filter((p) => !sinceIso || p.mergedAt > sinceIso)
    .sort((a, b) => (a.mergedAt < b.mergedAt ? 1 : a.mergedAt > b.mergedAt ? -1 : 0))
    .map((p) => `${p.title} (#${p.number})`);
}

export function renderStub(version, dateIso, entries, source) {
  const provenance = source === "pr-titles"
    ? "merged PR titles"
    : "commit subjects (PR titles unavailable — offline, or no PR-shaped merges since the last tag)";
  const bullets = entries.length
    ? entries.map((e) => `- ${e}`).join("\n")
    : "- (nothing found since the last tag — fill this in)";
  return `## v${version} — ${dateIso}\n\n<!-- Stub generated by \`pnpm release\` from ${provenance}. Edit before publishing. -->\n\n${bullets}\n`;
}

/** Newest release on top, `# Changelog` header kept (or created) above everything. */
export function prependChangelog(existing, stub) {
  if (existing === null) return `# Changelog\n\n${stub}`;
  const m = /^(# Changelog\n+)([\s\S]*)$/.exec(existing);
  if (m) return `${m[1]}${stub}\n${m[2]}`.replace(/\n{3,}$/, "\n");
  return `${stub}\n${existing}`;
}

/** Which of the three release artifacts are missing for this version. Matched by shape + version,
 *  not exact filename — electron-builder owns the naming. */
export function missingArtifacts(files, version) {
  const missing = [];
  if (!files.some((f) => f.endsWith(".dmg") && f.includes(version))) missing.push(`a ${version} .dmg`);
  if (!files.some((f) => f.endsWith(".zip") && f.includes(version))) missing.push(`a ${version} .zip`);
  if (!files.includes("latest-mac.yml")) missing.push("latest-mac.yml");
  return missing;
}

export function nextStepsText({ tag, branch, artifacts }) {
  const fileArgs = artifacts.map((f) => `apps/desktop/release/${f}`).join(" \\\n         ");
  return [
    ``,
    `Released ${tag} LOCALLY — nothing was pushed, nothing was published.`,
    ``,
    `Artifacts (apps/desktop/release/):`,
    ...artifacts.map((f) => `  ${f}`),
    ``,
    `Next steps — all manual, in order:`,
    `  1. Review the CHANGELOG.md stub for ${tag}; if you edit it:`,
    `       git add CHANGELOG.md && git commit --amend --no-edit`,
    `  2. Push the branch and the tag:`,
    `       git push origin ${branch} && git push origin ${tag}`,
    `  3. Create the GitHub release as a DRAFT with the artifacts:`,
    `       gh release create ${tag} --draft --title "Realm ${tag}" --notes "TODO" \\`,
    `         ${fileArgs}`,
    `     then paste the CHANGELOG.md section as the notes and publish the draft in the GitHub UI.`,
    `     Once published, this public release becomes the in-app feed for signed builds.`,
    ``,
  ].join("\n");
}

// ---------- orchestration (integration-tested with an injected exec) ----------

export function release({ root, argv, exec, log, smoke = smokeTestPackagedServer }) {
  const { kind, dryRun } = parseReleaseArgs(argv);

  const dirty = (exec("git", ["status", "--porcelain"], { cwd: root }) ?? "").trim();
  if (dirty) throw new Error(`working tree is not clean — commit or stash first:\n${dirty}`);

  const pkgPath = join(root, "apps", "desktop", "package.json");
  const pkgText = readFileSync(pkgPath, "utf8");
  const current = JSON.parse(pkgText).version;
  const next = bumpVersion(current, kind);
  const tag = `v${next}`;
  if ((exec("git", ["tag", "--list", tag], { cwd: root }) ?? "").trim()) throw new Error(`tag ${tag} already exists`);

  let lastTag = null;
  try { lastTag = (exec("git", ["describe", "--tags", "--abbrev=0"], { cwd: root }) ?? "").trim() || null; } catch { lastTag = null; }
  const subjects = (exec("git", ["log", lastTag ? `${lastTag}..HEAD` : "HEAD", "--pretty=%s"], { cwd: root }) ?? "")
    .split("\n").filter(Boolean);

  // The ladder: gh (10s budget, any failure is just a rung down) → git PR subjects → commit subjects.
  let entries = null;
  let source = null;
  try {
    const sinceIso = lastTag ? (exec("git", ["log", "-1", "--format=%cI", lastTag], { cwd: root }) ?? "").trim() : null;
    const ghJson = exec("gh", ["pr", "list", "--state", "merged", "--limit", "100", "--json", "number,title,mergedAt"], { cwd: root, timeout: 10_000 });
    const fromGh = entriesFromGh(JSON.parse(ghJson), sinceIso);
    if (fromGh.length) { entries = fromGh; source = "pr-titles"; }
  } catch { /* offline, gh missing, or unauthed — degrade to git, which is the same truth, humbler */ }
  if (!entries) ({ entries, source } = changelogEntries(subjects));

  const date = new Date().toISOString().slice(0, 10);
  const stub = renderStub(next, date, entries, source);
  const branch = (exec("git", ["rev-parse", "--abbrev-ref", "HEAD"], { cwd: root }) ?? "").trim();

  if (dryRun) {
    log(`[release] DRY RUN — nothing written. Plan:`);
    log(`  version: ${current} → ${next} (${kind}); tag ${tag} on branch ${branch}`);
    log(`  changelog stub (from ${source}${lastTag ? `, since ${lastTag}` : ", full history — no previous tag"}):`);
    log(stub.replace(/^/gm, "  | "));
    log(`  then: pnpm dist (dmg + zip + latest-mac.yml), commit "release: ${tag}", tag ${tag}. No push, no publish.`);
    return { next, tag, entries, source, dryRun: true };
  }

  // Bump BEFORE the build so the artifacts carry the released version.
  writeFileSync(pkgPath, bumpPackageJsonText(pkgText, next));
  const clPath = join(root, "CHANGELOG.md");
  writeFileSync(clPath, prependChangelog(existsSync(clPath) ? readFileSync(clPath, "utf8") : null, stub));

  log(`[release] building v${next} — pnpm dist (dmg + zip + latest-mac.yml)…`);
  try {
    exec("pnpm", ["dist"], { cwd: root, stdio: "inherit" });
  } catch (e) {
    throw new Error(`build failed — the version bump and changelog stub are left in the tree; NO commit or tag was made. Fix the build and re-run pnpm release after a git checkout -- . (or keep the stub).\n${e?.message ?? e}`);
  }

  const releaseDir = join(root, "apps", "desktop", "release");
  const files = existsSync(releaseDir) ? readdirSync(releaseDir) : [];
  const missing = missingArtifacts(files, next);
  if (missing.length) throw new Error(`build finished but artifacts are missing: ${missing.join(", ")} (release/ has: ${files.join(", ") || "nothing"}) — NO commit or tag was made`);

  log("[release] smoke-testing the packaged server…");
  smoke(root, log);

  exec("git", ["add", "apps/desktop/package.json", "CHANGELOG.md"], { cwd: root });
  exec("git", ["commit", "-m", `release: ${tag}`], { cwd: root });
  exec("git", ["tag", tag], { cwd: root });

  const artifacts = files.filter((f) => (f.includes(next) && (f.endsWith(".dmg") || f.endsWith(".zip"))) || f === "latest-mac.yml").sort();
  log(nextStepsText({ tag, branch, artifacts }));
  return { next, tag, entries, source, artifacts, dryRun: false };
}

// ---------- entry ----------

function main() {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const exec = (cmd, args, opts = {}) =>
    execFileSync(cmd, args, { encoding: "utf8", cwd: opts.cwd, timeout: opts.timeout, stdio: opts.stdio ?? ["ignore", "pipe", "pipe"] });
  try {
    release({ root, argv: process.argv.slice(2), exec, log: console.log });
  } catch (e) {
    console.error(`[release] ${e?.message ?? e}`);
    process.exit(1);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();

/**
 * Boot the server bundle that was just packaged, on a scratch home, and require it to say `ready`.
 *
 * v1.4.0 shipped a server that could not start: `@xterm/headless` is CommonJS and tsup leaves
 * anything in `dependencies` external, so the bundle carried a bare `import { Terminal } from
 * "@xterm/headless"` that Node refuses at load. Every gate was green — the suite passed, `tsc`
 * passed, `pnpm build` passed — because none of them RUN the bundle. The first execution was the
 * packaged app's, on a user's machine.
 *
 * So this executes it. `dist/main.js` prints one line of JSON when it is serving; anything else, or
 * nothing before the timeout, fails the release BEFORE the commit and the tag exist. It catches the
 * whole class — any top-level import that resolves at build time and explodes at load.
 *
 * REALM_HOME is a throwaway directory and the port is one nothing else uses: a release must never
 * touch the real `~/Realm`, whose database it would migrate.
 */
export function smokeTestPackagedServer(root, log = () => {}, timeoutMs = 60_000) {
  const entry = join(root, "apps", "server", "dist", "main.js");
  if (!existsSync(entry)) throw new Error(`no packaged server at ${entry} — NO commit or tag was made`);
  const home = mkdtempSync(join(tmpdir(), "realm-release-smoke-"));
  const logPath = join(home, "boot.log");
  /* The child writes to a FILE DESCRIPTOR, and this polls it with synchronous reads.
     The obvious version — `spawn` plus `child.stdout.on("data", …)` — cannot work here and failed
     silently the first time it ran: the wait below blocks the thread, so the event loop never turns,
     so those handlers never fire, so the output is always empty and every release "fails". Writing
     past Node's event loop is what makes a synchronous wait legitimate. */
  const fd = openSync(logPath, "a");
  const child = spawn(process.execPath, [entry], {
    cwd: join(root, "apps", "server"),
    env: { ...process.env, REALM_HOME: home, REALM_PORT: "8799" },
    stdio: ["ignore", fd, fd],
    detached: false,
  });
  const read = () => { try { return readFileSync(logPath, "utf8"); } catch { return ""; } };
  /* A crash names itself, so it is worth failing on immediately rather than waiting out the clock —
     these are the shapes a bundle that will not load actually produces. */
  const FATAL = /SyntaxError|Cannot find (module|package)|ERR_MODULE_NOT_FOUND|ERR_REQUIRE_ESM|MODULE_NOT_FOUND|ERR_UNKNOWN_BUILTIN_MODULE|ERR_UNSUPPORTED_DIR_IMPORT/;
  const deadline = Date.now() + timeoutMs;
  try {
    for (;;) {
      const out = read();
      if (out.includes('"type":"ready"')) { log("[release] packaged server booted."); return; }
      if (FATAL.test(out)) throw new Error(smokeFailure("it could not load", out));
      if (Date.now() >= deadline) throw new Error(smokeFailure("it never reported ready", out));
      execFileSync("sleep", ["0.25"]);
    }
  } finally {
    try { child.kill("SIGKILL"); } catch { /* already gone */ }
    try { closeSync(fd); } catch { /* already closed */ }
    try { rmSync(home, { recursive: true, force: true }); } catch { /* best effort */ }
  }
}

function smokeFailure(why, out) {
  return `the packaged server did not come up — ${why}. NO commit or tag was made.\n`
    + `This is the gate v1.4.0 did not have: the suite and the build cannot catch an import that\n`
    + `only fails when the bundle is executed.\n--- its output ---\n${(out || "(it printed nothing)").slice(0, 2000)}`;
}
