import { newId, type Checkpoint, type CheckpointKind } from "@realm/contracts";
import type { Db } from "../db/database";
import type { CapturedState } from "../workspace/checkpoints";
import { NotFoundError, now } from "./rows";

type Row = {
  id: string; environment_id: string; session_id: string | null; kind: CheckpointKind; label: string;
  ref: string; commit_sha: string; worktree_tree: string; index_tree: string;
  head_sha: string | null; head_ref: string | null;
  session_seq: number | null; provider_cursor: string | null; created_at: number;
};

/** The wire shape: everything a client can act on. The trees stay server-side — they are how `restore`
 *  works, not something a caller ever names. The two cursors DO travel, because what a restore will
 *  cost the conversation is exactly what the confirmation has to be able to say. */
const toCheckpoint = (r: Row): Checkpoint => ({
  id: r.id, environmentId: r.environment_id, sessionId: r.session_id, kind: r.kind, label: r.label,
  ref: r.ref, commitSha: r.commit_sha, headSha: r.head_sha, headRef: r.head_ref,
  sessionSeq: r.session_seq, providerCursor: r.provider_cursor, createdAt: r.created_at,
});
/** The git facts `CheckpointGit.restore` needs, read back off the row. */
const toState = (r: Row): CapturedState => ({
  commitSha: r.commit_sha, worktreeTree: r.worktree_tree, indexTree: r.index_tree,
  headSha: r.head_sha, headRef: r.head_ref,
});

export type CheckpointRecord = Checkpoint & { state: CapturedState };

/**
 * Rows indexing the hidden refs (Plan 7 W4).
 *
 * The store never touches git, and the git layer never touches the database: `CheckpointService` is the
 * only thing that knows both, and it is what guarantees a row and its ref live and die together.
 *
 * Ordering is `created_at DESC, rowid DESC` everywhere. Two checkpoints in one millisecond is not
 * hypothetical — a restore captures its `pre-restore` checkpoint microseconds before it runs — and the
 * rowid tiebreak is what stops "the newest" meaning two different things to two callers.
 */
export class CheckpointsStore {
  constructor(private db: Db) {}

  /** Newest first. `sessionId` narrows to one session's turns; null lists the whole environment. */
  list(environmentId: string, sessionId: string | null = null): Checkpoint[] {
    const rows = sessionId
      ? this.db.prepare("SELECT * FROM checkpoints WHERE environment_id = ? AND session_id = ? ORDER BY created_at DESC, rowid DESC").all(environmentId, sessionId)
      : this.db.prepare("SELECT * FROM checkpoints WHERE environment_id = ? ORDER BY created_at DESC, rowid DESC").all(environmentId);
    return (rows as Row[]).map(toCheckpoint);
  }

  get(id: string): CheckpointRecord | null {
    const r = this.db.prepare("SELECT * FROM checkpoints WHERE id = ?").get(id) as Row | undefined;
    return r ? { ...toCheckpoint(r), state: toState(r) } : null;
  }
  require(id: string): CheckpointRecord {
    const r = this.get(id); if (!r) throw new NotFoundError("checkpoint", id);
    return r;
  }

  /** Insert a row for a capture that has already happened. The id is generated by the CALLER, because
   *  it is baked into the ref name before the ref exists.
   *
   *  `sessionSeq` is written here and `provider_cursor` is not, because they are known at different
   *  moments: Realm's transcript position is a fact about NOW, and the provider cursor needs the
   *  discarded turn's prompt uuid, which does not exist until the turn this checkpoint fronts has been
   *  sent. `setProviderCursor` completes the row when that turn settles. */
  create(input: { id?: string; environmentId: string; sessionId: string | null; kind: CheckpointKind; label: string; ref: string; state: CapturedState; sessionSeq?: number | null }): Checkpoint {
    const id = input.id ?? newId();
    this.db.prepare(`INSERT INTO checkpoints
      (id, environment_id, session_id, kind, label, ref, commit_sha, worktree_tree, index_tree, head_sha, head_ref, session_seq, provider_cursor, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?)`)
      .run(id, input.environmentId, input.sessionId, input.kind, input.label, input.ref,
        input.state.commitSha, input.state.worktreeTree, input.state.indexTree,
        input.state.headSha, input.state.headRef, input.sessionSeq ?? null, now());
    return toCheckpoint(this.db.prepare("SELECT * FROM checkpoints WHERE id = ?").get(id) as Row);
  }

  /**
   * Write (or erase) where the PROVIDER's conversation stood for this checkpoint.
   *
   * Both directions are load-bearing. Writing completes a turn checkpoint once its turn has settled and
   * the discarded turn's prompt is known; writing NULL is what a provider refusal does, and it is
   * permanent on purpose — a fork the CLI has rejected is rejected deterministically, so a row that
   * went on advertising it would be an invitation to re-send a request that can only fail again.
   *
   * Silently does nothing for an id that is no longer there: a turn can settle after its checkpoint has
   * been pruned or its environment forgotten, and that is not a failure of the turn.
   */
  setProviderCursor(id: string, cursor: string | null): void {
    this.db.prepare("UPDATE checkpoints SET provider_cursor = ? WHERE id = ?").run(cursor, id);
  }

  /**
   * The checkpoints retention would drop for this environment: everything past `keep`, oldest first,
   * MINUS the ones that must survive.
   *
   * Two exemptions, and both are the difference between a retention policy and a way to lose work:
   *
   *  - the newest checkpoint overall, so an environment always has something to go back to;
   *  - the newest `pre-restore` checkpoint, which is the undo of the last restore. It is the only copy
   *    of the state a restore overwrote, and it is by construction older than everything the restore
   *    then produced — so a plain "drop the oldest" rule deletes exactly it, first.
   */
  prunable(environmentId: string, keep: number): Checkpoint[] {
    const all = this.list(environmentId);
    if (all.length <= keep) return [];
    const protectedIds = new Set<string>();
    if (all[0]) protectedIds.add(all[0].id);
    const undo = all.find((c) => c.kind === "pre-restore");
    if (undo) protectedIds.add(undo.id);
    // Newest `keep` stay; of the rest, the protected ones stay too.
    return all.slice(keep).filter((c) => !protectedIds.has(c.id)).reverse();
  }

  delete(ids: string[]): void {
    if (ids.length === 0) return;
    const stmt = this.db.prepare("DELETE FROM checkpoints WHERE id = ?");
    for (const id of ids) stmt.run(id);
  }

  /** Every ref this environment's rows name — what `forgetEnvironment` deletes from git before the
   *  rows cascade away with the environment. */
  refs(environmentId: string): string[] {
    return (this.db.prepare("SELECT ref FROM checkpoints WHERE environment_id = ?").all(environmentId) as { ref: string }[]).map((r) => r.ref);
  }
}
