import { describe, expect, it, beforeEach } from "vitest";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { openDatabase, type Db } from "../db/database";
import { ProfilesStore } from "./profiles";
import { SpacesStore } from "./spaces";
import { EnvironmentsStore } from "./environments";
import { SessionsStore } from "./sessions";
import { McpServersStore, McpCallLogStore, type McpServerInput } from "./mcp";

let db: Db; let servers: McpServersStore; let calls: McpCallLogStore;

const stdio = (name: string): McpServerInput =>
  ({ name, transport: "stdio", command: "/usr/bin/node", args: ["/abs/s.mjs"], url: "", secrets: { KEY: "pat-x" } });

beforeEach(() => {
  db = openDatabase(join(mkdtempSync(join(tmpdir(), "realm-mcpstore-")), "realm.db"));
  servers = new McpServersStore(db);
  calls = new McpCallLogStore(db);
});

describe("McpServersStore — tools and oauth cache", () => {
  it("starts every server with an empty tool cache and no oauth connection", () => {
    const s = servers.create(stdio("airtable"));
    expect(s.tools).toEqual([]);
    expect(s.oauthJson).toBe("");
  });

  it("round-trips setTools", () => {
    const s = servers.create(stdio("airtable"));
    servers.setTools(s.id, [{ name: "search", description: "Search records" }, { name: "create", description: "Create a record" }]);
    expect(servers.get(s.id)!.tools).toEqual([{ name: "search", description: "Search records" }, { name: "create", description: "Create a record" }]);
  });

  it("round-trips setOauth as an opaque blob", () => {
    const s = servers.create(stdio("airtable"));
    servers.setOauth(s.id, JSON.stringify({ accessToken: "tok" }));
    expect(servers.get(s.id)!.oauthJson).toBe(JSON.stringify({ accessToken: "tok" }));
  });

  it("neither setTools nor setOauth runs the name guard, because they are not user edits", () => {
    // The named mutant: routing either through update() and thereby refusing on some unrelated
    // condition, or letting a cache write collide with the UNIQUE-name check.
    const a = servers.create(stdio("airtable"));
    servers.create(stdio("other"));
    expect(() => servers.setTools(a.id, [])).not.toThrow();
    expect(() => servers.setOauth(a.id, "{}")).not.toThrow();
  });

  it("degrades a corrupted tools_json to [] rather than making the row unreadable", () => {
    const s = servers.create(stdio("airtable"));
    db.prepare("UPDATE mcp_servers SET tools_json = ? WHERE id = ?").run("not json", s.id);
    expect(servers.get(s.id)!.tools).toEqual([]);
    db.prepare("UPDATE mcp_servers SET tools_json = ? WHERE id = ?").run(JSON.stringify([{ name: "x" }, "garbage", { name: "y", description: "d" }]), s.id);
    // A malformed entry (missing description) is dropped; a well-formed one alongside it survives.
    expect(servers.get(s.id)!.tools).toEqual([{ name: "y", description: "d" }]);
    db.close();
  });

  it("setTools/setOauth on an unknown id report NOT_FOUND rather than silently no-oping", () => {
    expect(() => servers.setTools("01ARZ3NDEKTSV4RRFFQ69G5FAZ", [])).toThrow(/not found/);
    expect(() => servers.setOauth("01ARZ3NDEKTSV4RRFFQ69G5FAZ", "{}")).toThrow(/not found/);
  });
});

describe("McpCallLogStore", () => {
  let sessionId: string; let serverId: string;

  beforeEach(() => {
    const home = mkdtempSync(join(tmpdir(), "realm-mcplog-home-"));
    const p = new ProfilesStore(db).create({ name: "P", icon: "x", color: "#000" });
    const spaces = new SpacesStore(db, home);
    const envs = new EnvironmentsStore(db);
    const sessions = new SessionsStore(db);
    const spaceId = spaces.create({ profileId: p.id, name: "Work", icon: "folder" }).id;
    const envId = envs.ensurePrimary(spaceId).id;
    sessionId = sessions.create({ spaceId, projectId: null, agentKind: "claude", model: null, effort: null, permissionMode: "default", environmentId: envId, title: "s" }).id;
    serverId = servers.create(stdio("airtable")).id;
  });

  const row = (over: Partial<Parameters<McpCallLogStore["append"]>[0]> = {}) => ({
    sessionId, serverId, serverName: "airtable", tool: "search", argsJson: "{}",
    resultSummary: "3 records", ok: true, durationMs: 12, ...over,
  });

  it("append returns the full row, id and ts generated by the store", () => {
    const r = calls.append(row());
    expect(r.id).toBeTruthy();
    expect(r.ts).toBeGreaterThan(0);
    expect(r).toMatchObject({ sessionId, serverId, serverName: "airtable", tool: "search", ok: true, durationMs: 12 });
  });

  it("orders newest first, breaking a same-millisecond tie by insertion order", () => {
    const a = calls.append(row({ tool: "a" }));
    const b = calls.append(row({ tool: "b" }));
    const c = calls.append(row({ tool: "c" }));
    // Force the tie: three inserts usually land in one millisecond, but "usually" would make this
    // test tell the truth only most of the time.
    db.exec("UPDATE mcp_call_log SET ts = 5");
    expect(calls.list().map((x) => x.id)).toEqual([c.id, b.id, a.id]);
  });

  it("filters by sessionId", () => {
    const otherSessionId = new SessionsStore(db).create({
      spaceId: (db.prepare("SELECT space_id FROM sessions WHERE id = ?").get(sessionId) as { space_id: string }).space_id,
      projectId: null, agentKind: "claude", model: null, effort: null, permissionMode: "default",
      environmentId: (db.prepare("SELECT environment_id FROM sessions WHERE id = ?").get(sessionId) as { environment_id: string }).environment_id,
      title: "other",
    }).id;
    const mine = calls.append(row());
    calls.append(row({ sessionId: otherSessionId }));
    expect(calls.list({ sessionId }).map((c) => c.id)).toEqual([mine.id]);
  });

  it("filters by serverId", () => {
    const other = servers.create(stdio("vercel"));
    const mine = calls.append(row());
    calls.append(row({ serverId: other.id, serverName: "vercel" }));
    expect(calls.list({ serverId }).map((c) => c.id)).toEqual([mine.id]);
  });

  it("pages backward with `before` as a ts cursor", () => {
    const a = calls.append(row({ tool: "a" })); db.prepare("UPDATE mcp_call_log SET ts = 100 WHERE id = ?").run(a.id);
    const b = calls.append(row({ tool: "b" })); db.prepare("UPDATE mcp_call_log SET ts = 200 WHERE id = ?").run(b.id);
    const c = calls.append(row({ tool: "c" })); db.prepare("UPDATE mcp_call_log SET ts = 300 WHERE id = ?").run(c.id);
    expect(calls.list({ before: 300 }).map((x) => x.id)).toEqual([b.id, a.id]);
    expect(calls.list({ before: 200 }).map((x) => x.id)).toEqual([a.id]);
  });

  it("defaults the limit to 50 and caps it at 200", () => {
    for (let i = 0; i < 210; i++) calls.append(row({ tool: `t${i}` }));
    expect(calls.list()).toHaveLength(50);
    expect(calls.list({ limit: 5 })).toHaveLength(5);
    expect(calls.list({ limit: 500 })).toHaveLength(200); // asked for more than the cap, with more than 200 rows available
  });

  it("survives its server row being deleted — serverId comes back null, the call stays", () => {
    const r = calls.append(row());
    servers.delete(serverId);
    expect(calls.list().find((c) => c.id === r.id)!.serverId).toBeNull();
  });
});
