/**
 * Live check of the Graphify integration against the REAL `graphify` CLI.
 *
 * Three claims here cannot be held up by a unit test, because each one is really a claim about a
 * third-party artifact Realm does not control:
 *
 *   1. `graphify-mcp` is reachable through the real `McpHub` when it is configured by BARE command
 *      name. The hub passes `env: row.secrets` to `StdioClientTransport`, which looks like it would
 *      spawn with no PATH; the SDK merges `getDefaultEnvironment()` under it, so it does not. A test
 *      with a stub transport proves nothing about that merge — only a real spawn does.
 *   2. The tool names the graph server advertises are the ones Realm's gateway will forward. They are
 *      graphify's to rename at any release, so this asserts against the live list, not a fixture.
 *   3. `graphify update` writes a `graph.html` whose only script tag is a CDN one, which
 *      `localizeVisNetwork` must rewrite for the guide CSP. That markup is regenerated by every
 *      extraction, so a committed fixture of it decays silently — this reads what graphify just wrote.
 *
 * It writes nothing outside its own scratch home and temp workspace, and never touches ~/Realm.
 *
 *   pnpm --filter @realm/server exec tsx scripts/live-graphify-check.ts
 *
 * Exits non-zero if any check fails. A missing `graphify` is reported as a skip, not a pass.
 */
import { execFile } from "node:child_process";
import { cpSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { McpHub } from "../src/mcp/hub";
import { McpService } from "../src/mcp/service";
import { McpServersStore } from "../src/store/mcp";
import { SettingsStore } from "../src/store/settings";
import { ProfilesStore } from "../src/store/profiles";
import { SpacesStore } from "../src/store/spaces";
import { DocumentPreviewServer, defaultVisNetworkDir } from "../src/documents/preview";
import { openDatabase } from "../src/db/database";
import { probeGraphify } from "../src/graphify/probe";
import { finish, ok } from "./harness";

const run = promisify(execFile);
/** Extraction shells out to tree-sitter over every file in the tree; the sample here is two files. */
const EXTRACT_TIMEOUT_MS = 120_000;
/** The subset of graphify's tools Realm's gateway is expected to forward. Not the whole list — the PR
 *  dashboard tools need a GitHub remote, and asserting on them would make this check need one too. */
const EXPECTED_TOOLS = ["query_graph", "get_node", "get_neighbors", "god_nodes", "graph_stats", "shortest_path"];
/** Two real source files, so the graph has genuine cross-file edges rather than a synthetic shape. */
const SAMPLE = ["mcp.ts", "attachments.ts"];

async function main() {
  const probe = await probeGraphify();
  if (!probe.available) {
    console.log(`  SKIP  graphify is not installed — ${probe.reason ?? ""}`);
    console.log(`        install it with: uv tool install "graphifyy[mcp]"`);
    finish();
  }
  ok("graphify reports a version", probe.version !== null, probe.version ?? "(none)");

  const home = mkdtempSync(join(tmpdir(), "realm-graphify-live-"));
  const work = mkdtempSync(join(tmpdir(), "realm-graphify-work-"));
  const contracts = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "packages", "contracts", "src");
  for (const f of SAMPLE) cpSync(join(contracts, f), join(work, f));

  await run("graphify", ["update", "."], { cwd: work, timeout: EXTRACT_TIMEOUT_MS });
  const graphPath = join(work, "graphify-out", "graph.json");
  const graph = JSON.parse(readFileSync(graphPath, "utf8")) as { nodes: unknown[]; links: unknown[] };
  ok("the extraction produced a non-empty graph", graph.nodes.length > 0, `${graph.nodes.length} nodes, ${graph.links.length} links`);

  // Through the hub, not `mcp.test`: the test button spawns with the inherited environment, so it
  // would pass on a PATH the hub never sees. The hub is what a session actually talks to.
  const db = openDatabase(join(home, "realm.db"));
  const servers = new McpServersStore(db);
  const mcp = new McpService({ servers, settings: new SettingsStore(db) });
  const profile = new ProfilesStore(db).create({ name: "Graphify live", icon: "home", color: "#7c6cff" });
  const space = new SpacesStore(db, home).create({ profileId: profile.id, name: "Mine", icon: "home" });
  // Bare command name on purpose — an absolute path here would pass whether or not the SDK's env merge
  // does what claim 1 above says it does, which is the only reason this line is interesting.
  const row = mcp.add({ name: "graphify", transport: "stdio", command: "graphify-mcp", args: [graphPath] }, space.id);

  const hub = new McpHub({ servers, authHeaders: async () => ({}), onStatus: () => {} });
  let tools: string[] = [];
  try {
    tools = (await hub.tools(row.id)).map((t) => t.name);
  } catch (e) {
    ok("the graph server was reachable through the hub", false, e instanceof Error ? e.message : String(e));
  }
  ok("the graph server was reachable through the hub", tools.length > 0, `${tools.length} tools`);
  const missing = EXPECTED_TOOLS.filter((t) => !tools.includes(t));
  ok("it advertises the graph tools Realm expects to forward", missing.length === 0, missing.length ? `missing: ${missing.join(", ")}` : tools.join(", "));

  const stats = await hub.call(row.id, "graph_stats", {});
  const text = (stats.content as { type: string; text?: string }[]).map((c) => c.text ?? "").join("");
  ok("a tool call through the hub answers about the real graph", text.includes(String(graph.nodes.length)), text.slice(0, 120).replace(/\n/g, " "));

  // The same file, through the server the documents pane frames it with.
  const vis = defaultVisNetworkDir();
  ok("the vis-network bundle is vendored", vis !== null, vis ?? "not resolvable");
  const preview = new DocumentPreviewServer({ rootOf: (id) => (id === "ws" ? work : null), katexDir: null, visNetworkDir: vis });
  const port = await preview.listen();
  const get = (p: string) => fetch(`http://127.0.0.1:${port}/p/${preview.token}${p}`);

  const page = await get("/ws/graphify-out/graph.html");
  const html = await page.text();
  ok("the generated graph is served", page.status === 200, `HTTP ${page.status}`);
  // If graphify ever inlines its bundle, this stops being a rewrite and starts being a no-op — which is
  // fine, but the assertion below would then be vacuous, so check the input still looks like the problem.
  const raw = readFileSync(join(work, "graphify-out", "graph.html"), "utf8");
  ok("graphify still ships a remote bundle to rewrite", /<script[^>]+src="https?:\/\/[^"]*vis-network/.test(raw));
  ok("no remote script survives into what the pane frames", !/src="https?:\/\//.test(html), (html.match(/src="https?:\/\/[^"]*/) ?? [""])[0]);
  ok("it points at the vendored bundle instead", html.includes("/_realm/vis-network/vis-network.min.js"));
  // graphify ships an SRI hash of the CDN build. Left in place it silently blocks the vendored one —
  // the markup looks correct and the graph is still blank, so assert on it here and not just in a unit test.
  ok("no integrity hash survives to block the vendored bundle", !html.includes("integrity"), (html.match(/integrity="[^"]*"/) ?? [""])[0]);

  const bundle = await get("/_realm/vis-network/vis-network.min.js");
  ok("and that bundle is served", bundle.status === 200 && (bundle.headers.get("content-type") ?? "").includes("javascript"), `HTTP ${bundle.status}`);

  await preview.close();
  await hub.close();
  db.close();
  rmSync(home, { recursive: true, force: true });
  rmSync(work, { recursive: true, force: true });
  finish();
}

main().catch((e) => { console.error("driver crashed:", e); process.exit(2); });
